const { CHARACTERS, WEAPONS, PASSIVES, AFFIXES, ENEMIES, BOSSES, RUN_SECONDS, WORLD } = require('../../utils/config');

const SAVE_KEY = 'ruins_survivor_meta_v1';
const SNAP_KEY = 'ruins_survivor_run_v1';
const TALENTS = { hp: '最大生命', damage: '伤害', speed: '移动速度', pickup: '拾取范围', gold: '开局金币' };
const TALENT_COSTS = [25, 50, 90, 140, 200];
const DIFFICULTIES = [{name:'废墟 I',text:'标准难度',hp:1,damage:1,spawn:1},{name:'废墟 II',text:'敌人生命 +25% · 数量 +10%',hp:1.25,damage:1.1,spawn:1.1},{name:'废墟 III',text:'敌人生命 +55% · 词缀提前出现',hp:1.55,damage:1.2,spawn:1.18},{name:'废墟 IV',text:'敌人生命 +90% · 首领技能强化',hp:1.9,damage:1.35,spawn:1.28},{name:'废墟 V',text:'敌人生命 +140% · 精英双词缀',hp:2.4,damage:1.55,spawn:1.4}];
const DAILY_RULES = [{id:'abundance',name:'经验丰收',text:'经验晶体价值 +25%'},{id:'firepower',name:'火力祝福',text:'全伤害 +12%'},{id:'march',name:'急行军',text:'移动速度 +12%'},{id:'salvage',name:'古物交易',text:'金币收益 +50%'},{id:'bounty',name:'首领悬赏',text:'精英与首领奖励提高'}];
const ACHIEVEMENTS = [{id:'first_boss',name:'弑首者',text:'击败任意首领',reward:30},{id:'evolver',name:'淬炼完成',text:'单局进化 3 把武器',reward:35},{id:'slayer',name:'百斩幸存者',text:'单局击败 500 名敌人',reward:40},{id:'hard_win',name:'废墟征服者',text:'在废墟 III 或更高难度通关',reward:60},{id:'full_house',name:'全副武装',text:'单局持有 6 把武器',reward:45}];
const rnd = (a, b) => a + Math.random() * (b - a);
const clamp = (n, a, b) => Math.min(b, Math.max(a, n));
const distance = (a, b) => Math.hypot(a.x - b.x, a.y - b.y);
const hasAffix = (e, id) => e.affix === id || e.affix2 === id;
const timeText = (v) => `${String(Math.max(0, Math.floor(v / 60))).padStart(2, '0')}:${String(Math.max(0, Math.floor(v % 60))).padStart(2, '0')}`;
const emptyModal = () => ({ type: '', title: '', subtitle: '' });
const defaultMeta = () => ({ coins: 0, runs: 0, kills: 0, wins: 0, best: 0, bestEndlessCycle: 0, bestEndlessTime: 0, difficulty: 1, unlockedDifficulty: 1, discoveries: { weapons: {}, evolved: {}, affixes: {}, bosses: {} }, achievements: {}, affixRewards: {}, dailyClaimed: '', talents: { hp: 0, damage: 0, speed: 0, pickup: 0, gold: 0 }, settings: { sound: true, music: true, lowQuality: false, tutorial: true } });

Page({
  data: {
    screen: 'menu', meta: defaultMeta(), settings: defaultMeta().settings, characters: [], selected: 'watchman', currentCharacter: CHARACTERS[0], hasSnapshot: false,
    hud: { hpPercent: 100, xpPercent: 0, hpText: '130/130', levelText: '01', chapter: '第一幕 · 灰烬苏醒', time: '00:00', objective: '下一事件 05:00', coins: 0, kills: 0, weaponList: [], passiveList: [], bossVisible: false, bossPercent: 100, bossName: '首领', hordeVisible: false, hordeText: '' },
    stick: { x: 0, y: 0 }, toast: '', modal: emptyModal(), rerolls: 2, replayTab: 'challenge', dailyRule: DAILY_RULES[0], ui: { rightTop: 46, rightGap: 12 },
  },

  onLoad() {
    let saved = defaultMeta();
    try { saved = Object.assign(saved, wx.getStorageSync(SAVE_KEY) || {}); } catch (_) {}
    saved.talents = Object.assign(defaultMeta().talents, saved.talents || {});
    saved.settings = Object.assign(defaultMeta().settings, saved.settings || {});
    this.audioPool = {}; this.musicAudio = null; this.audioIndex = {};
    saved.discoveries=Object.assign(defaultMeta().discoveries,saved.discoveries||{});Object.keys(saved.discoveries).forEach(k=>saved.discoveries[k]=Object.assign({},defaultMeta().discoveries[k],saved.discoveries[k]||{}));saved.achievements=saved.achievements||{};saved.achievementClaimed=saved.achievementClaimed||{};saved.affixRewards=saved.affixRewards||{};saved.unlockedDifficulty=Math.max(1,saved.unlockedDifficulty||1);
    this.meta = saved;
    this.measureChrome();
    this.refreshMenu();this.playMusic('lobby');
  },

  measureChrome() {
    try {
      const info = wx.getWindowInfo ? wx.getWindowInfo() : wx.getSystemInfoSync();
      const capsule = wx.getMenuButtonBoundingClientRect ? wx.getMenuButtonBoundingClientRect() : null;
      const rightTop = capsule && capsule.bottom ? capsule.bottom + 6 : 46;
      const rightGap = capsule && capsule.right ? Math.max(10, info.windowWidth - capsule.right) : 12;
      this.setData({ ui: { rightTop, rightGap } });
    } catch (_) {}
  },

  onReady() { this.initCanvas(); },
  onHide() { if (this.phase === 'playing') this.pauseGame(); this.pauseAudio(); },
  onUnload() { this.destroyed = true; this.stopCanvasLoop(); this.saveSnapshot(); this.destroyAudio(); },

  playMusic(track) { if(!this.meta.settings.music)return;if(!this.musicAudio){this.musicAudio=wx.createInnerAudioContext();this.musicAudio.loop=true;this.musicAudio.volume=.28;}const src=`https://oss.zyg8.top/game/assets/audio/music_${track}.mp3`;if(this.musicAudio.src!==src){this.musicAudio.stop();this.musicAudio.src=src;}this.musicAudio.play(); },
  pauseAudio() { if(this.musicAudio)this.musicAudio.pause();Object.keys(this.audioPool||{}).forEach(k=>this.audioPool[k].forEach(a=>a.stop())); },
  destroyAudio() { if(this.musicAudio){this.musicAudio.destroy();this.musicAudio=null;}Object.keys(this.audioPool||{}).forEach(k=>this.audioPool[k].forEach(a=>a.destroy()));this.audioPool={}; },
  playSound(name) { if(!this.meta.settings.sound)return;const src=`https://oss.zyg8.top/game/assets/audio/sfx_${name}.mp3`;let pool=this.audioPool[src];if(!pool){pool=(['hit','boss_attack','skill'].includes(name)?[0,1]:[0]).map(()=>{const a=wx.createInnerAudioContext();a.src=src;a.volume=.72;return a;});this.audioPool[src]=pool;}const i=this.audioIndex[src]||0,a=pool[i];this.audioIndex[src]=(i+1)%pool.length;a.stop();a.play(); },

  refreshMenu() {
    let hasSnapshot = false; try { hasSnapshot = !!wx.getStorageSync(SNAP_KEY); } catch (_) {}
    const list = CHARACTERS.map(c => ({ ...c, selected: c.id === this.data.selected, unlocked: c.id === 'watchman' || (c.id === 'ember' && this.meta.kills >= 3000) || (c.id === 'gale' && this.meta.best >= 720), unlockText: c.id === 'ember' ? '累计击败 3000 敌人' : '任意角色存活 12 分钟' }));
    const daily=this.getDailyRule(),difficulty=DIFFICULTIES[this.meta.difficulty-1]||DIFFICULTIES[0];this.setData({ meta: this.meta, settings: this.meta.settings, characters: list, hasSnapshot,dailyRule:daily,difficultyName:difficulty.name });
  },

  getDailyRule() { const d=new Date(),key=`${d.getFullYear()}-${d.getMonth()+1}-${d.getDate()}`,seed=d.getFullYear()*372+(d.getMonth()+1)*31+d.getDate();return {...DAILY_RULES[seed%DAILY_RULES.length],date:key}; },

  saveMeta() { try { wx.setStorageSync(SAVE_KEY, this.meta); } catch (_) {} },

  selectCharacter(e) {
    const id = e.currentTarget.dataset.id, found = this.data.characters.find(c => c.id === id);
    if (!found || !found.unlocked) return;
    this.setData({ selected: id }); this.refreshMenu();this.playMusic('lobby');
  },

  initCanvas() {
    wx.createSelectorQuery().in(this).select('#gameCanvas').fields({ node: true, size: true }).exec(res => {
      if (!res[0]) return;
      const { node, width, height } = res[0], dpr = wx.getWindowInfo ? wx.getWindowInfo().pixelRatio : wx.getSystemInfoSync().pixelRatio;
      node.width = width * dpr; node.height = height * dpr;
      const ctx = node.getContext('2d'); ctx.scale(dpr, dpr);
      this.canvas = node; this.ctx = ctx; this.viewport = { width, height, dpr }; this.lastTime = Date.now();
      this.monsterImages = {}; this.bossEffectImages = {}; this.heroImages = {}; this.skillImages = {};
      this.canvasLoop = () => { if (this.destroyed) return; this.frame = null; if (this.run && this.phase === 'playing' && this.data.screen === 'game') { const now = Date.now(); let elapsed = Math.min(.2, Math.max(0, (now - this.lastTime) / 1000)); this.lastTime = now; while (elapsed > 0 && this.phase === 'playing') { const step = Math.min(.033, elapsed); this.update(step); elapsed -= step; } } this.draw(); if (this.run && this.phase === 'playing' && this.data.screen === 'game') this.frame = node.requestAnimationFrame(this.canvasLoop); };
      this.draw();
      if (this.phase === 'playing') this.startCanvasLoop();
    });
  },

  newRun(characterId) {
    const c = CHARACTERS.find(x => x.id === characterId) || CHARACTERS[0];
    const maxHp = c.hp * (1 + this.meta.talents.hp * .06),hazardPool=['fissure','poison','storm','dark'],hazards=[0,1].map((_,i)=>({type:hazardPool.splice(Math.floor(Math.random()*hazardPool.length),1)[0],start:i?720:360,end:i?780:420,started:false,tick:0}));
    return { character: c.id, x: WORLD.width / 2, y: WORLD.height / 2, hp: maxHp, maxHp, time: 0, level: 1, xp: 0, xpNeed: 15, kills: 0, coins: this.meta.talents.gold * 5,difficulty:this.meta.difficulty||1,dailyRule:this.getDailyRule().id,characterSkillCd:0,
      weapons: { [c.weapon]: 1 }, passives: {}, evolved: [], timers: {}, endless: false, endlessCycle: 0, cycleStart: 0, refine: 0, tome: { on: false, cd: {} }, tomeAngle: 0, shieldUp: false, phoenixUsed: false, stealAcc: 0, stealTimer: 0, enemies: [], projectiles: [], pickups: [], zones: [], particles: [], damageText: [], bullets: [], lastX: 1, lastY: 0,
      spawnTimer: 0, invuln: 0, snapshotTimer: 0, rerolls: 2, lockedChoice: null, altar: null, supplies: [], hazards, supplyPowerUntil: 0, warned: {}, events: {}, horde: null, id: 0, freezeUntil: 0, shake: 0 };
  },

  startGame() {
    let snapshot = null; try { snapshot = wx.getStorageSync(SNAP_KEY); } catch (_) {}
    this.run = snapshot ? Object.assign(this.newRun(snapshot.character), snapshot, { enemies: (snapshot.enemies||[]).map(e=>({...e})), projectiles: [], pickups: [], zones: [], particles: [], damageText: [], bullets: [] }) : this.newRun(this.data.selected);
    this.run.difficulty=this.run.difficulty||this.meta.difficulty||1;this.run.dailyRule=this.run.dailyRule||this.getDailyRule().id;this.run.characterSkillCd=this.run.characterSkillCd||0;this.meta.discoveries.weapons[this.run.character==='watchman'?'blade':this.run.character==='ember'?'flame':'boomerang']=true;this.saveMeta();
    if(snapshot&&this.run.time>=600&&!this.run.events.midbossDefeated&&this.run.time<900)this.run.events.b10=false;
    if(snapshot&&this.run.time>=900&&!this.run.events.finalbossDefeated)this.run.events.b15=false;
    if(snapshot&&!this.run.endless&&this.run.events.finalbossDefeated){this.run.events.finalbossDefeated=false;this.run.events.b15=false;}
    const c = CHARACTERS.find(x => x.id === this.run.character);
    this.phase = 'playing'; this.input = { x: 0, y: 0 }; this.lastTime = Date.now();
    this.setData({ screen: 'game', currentCharacter: c, modal: emptyModal(), rerolls: this.run.rerolls, stick: { x: 0, y: 0 } }); this.startCanvasLoop();
    this.playMusic(this.run.enemies.some(e=>e.bossId&&!e.dead)?'boss':'battle');
    this.syncHud(true);
    if (this.meta.settings.tutorial && !snapshot) { this.showToast('拖动左下摇杆移动，武器会自动攻击', 4500); this.meta.settings.tutorial = false; this.saveMeta(); }
  },

  retryGame() { try { wx.removeStorageSync(SNAP_KEY); } catch (_) {} this.startGame(); },
  backToMenu() { this.stopCanvasLoop(); this.phase = 'menu'; this.run = null; this.setData({ screen: 'menu', modal: emptyModal(), toast: '' }); this.refreshMenu(); this.playMusic('lobby'); },

  pauseGame() {
    if (!this.run || this.phase !== 'playing') return;
    this.phase = 'paused'; this.stopCanvasLoop(); this.saveSnapshot(); this.pauseAudio();
    this.setData({ modal: { type: 'pause', title: '已暂停', subtitle: '战斗时间已停止' } });
  },
  resumeGame() { this.phase = 'playing'; this.lastTime = Date.now(); this.setData({ modal: emptyModal() });this.playMusic(this.run.enemies.some(e=>e.bossId&&!e.dead)?'boss':'battle'); this.startCanvasLoop(); },
  quitGame() { this.finishRun('quit'); },

  saveSnapshot() {
    if (!this.run || !['playing', 'paused'].includes(this.phase)) return;
    const r = this.run;
    const snapshot = { character: r.character, x: r.x, y: r.y, hp: r.hp, maxHp: r.maxHp, time: r.time, level: r.level, xp: r.xp, xpNeed: r.xpNeed, kills: r.kills, coins: r.coins, weapons: r.weapons, passives: r.passives, evolved: r.evolved, timers: r.timers, rerolls: r.rerolls, lockedChoice: r.lockedChoice||null, altar: r.altar, supplies: r.supplies||[], hazards: r.hazards||[], supplyPowerUntil: r.supplyPowerUntil||0, difficulty:r.difficulty||1,dailyRule:r.dailyRule||'',characterSkillCd:r.characterSkillCd||0,warned: r.warned, events: r.events, horde: r.horde, endless: r.endless, endlessCycle: r.endlessCycle, cycleStart: r.cycleStart, refine: r.refine, tome: r.tome, tomeAngle: r.tomeAngle, shieldUp: !!r.shieldUp, phoenixUsed: !!r.phoenixUsed, stealAcc: r.stealAcc||0, stealTimer: r.stealTimer||0, id: r.id, enemies: r.enemies.filter(e=>!e.split).map(e=>({...e})) };
    try { wx.setStorageSync(SNAP_KEY, snapshot); } catch (_) {}
  },

  finishRun(result) {
    if (!this.run || this.phase === 'result') return;this.pauseAudio();this.playSound(result==='win'?'victory':'defeat');
    this.phase = 'result'; const r = this.run;
    if (r.endless) { this.meta.bestEndlessCycle = Math.max(this.meta.bestEndlessCycle, r.endlessCycle); this.meta.bestEndlessTime = Math.max(this.meta.bestEndlessTime, Math.floor(r.time)); }
    const base = result === 'win' ? 35 : result === 'quit' ? 0 : Math.round(8 + r.time / 45 + r.kills * .03) + (r.endless ? r.endlessCycle * 6 : 0);
    const gained = (result === 'quit' ? Math.floor(r.coins * .5) : r.coins) + base;
    this.meta.coins += gained; this.meta.runs++; this.meta.kills += r.kills; this.meta.best = Math.max(this.meta.best, Math.floor(r.time)); if (result === 'win') this.meta.wins++;
    if(result==='win'){this.meta.unlockedDifficulty=Math.max(this.meta.unlockedDifficulty,Math.min(5,1+Math.floor(this.meta.wins/2)));if(r.difficulty>=3)this.meta.achievements.hard_win=true;}if(r.kills>=500)this.meta.achievements.slayer=true;if(Object.keys(r.weapons).length>=6)this.meta.achievements.full_house=true;if((r.evolved||[]).length>=3)this.meta.achievements.evolver=true;if(['gravewarden','abysswatcher'].some(id=>r.events[`defeated_${id}`]))this.meta.achievements.first_boss=true;const today=this.getDailyRule().date;if(r.dailyRule===this.getDailyRule().id&&this.meta.dailyClaimed!==today&&result==='win'){this.meta.dailyClaimed=today;this.meta.coins+=20;this.showToast('每日契约完成 · 额外获得 20 金币',2600);}const achievementRewards={first_boss:30,evolver:35,slayer:40,hard_win:60,full_house:45};Object.keys(achievementRewards).forEach(id=>{if(this.meta.achievements[id]&&!this.meta.achievementClaimed[id]){this.meta.achievementClaimed=this.meta.achievementClaimed||{};this.meta.achievementClaimed[id]=true;this.meta.coins+=achievementRewards[id];}});
    this.saveMeta(); try { wx.removeStorageSync(SNAP_KEY); } catch (_) {}
    this.vibrate('heavy');
    this.setData({ modal: { type: 'result', title: result === 'win' ? '胜利 · 废墟幸存者' : r.endless ? `无尽轮回 · 止步第 ${r.endlessCycle} 层` : result === 'lose' ? '本局失败' : '对局结束', subtitle: r.endless ? `无尽存活 ${timeText(r.time - 900)} · 总时长 ${timeText(r.time)}` : '本局成长与奖励已结算', time: timeText(r.time), kills: r.kills, coins: gained, endlessCycle: r.endless ? r.endlessCycle : 0 } });
  },

  openTalent() {
    if(this.phase==='menu')this.playMusic('lobby');const talents = Object.keys(TALENTS).map(id => { const level = this.meta.talents[id], cost = TALENT_COSTS[level]; return { id, name: TALENTS[id], level, disabled: level >= 5 || this.meta.coins < cost, costText: level >= 5 ? '已满级' : `${cost} 金币` }; });
    this.setData({ modal: { type: 'talent', title: '通用天赋', subtitle: `现有金币 ${this.meta.coins}`, talents } });
  },
  buyTalent(e) { const id = e.currentTarget.dataset.id, level = this.meta.talents[id], cost = TALENT_COSTS[level]; if (level >= 5 || this.meta.coins < cost) return; this.meta.coins -= cost; this.meta.talents[id]++; this.saveMeta(); this.refreshMenu(); this.openTalent(); },
  resetTalents() { Object.keys(this.meta.talents).forEach(id => { for (let i = 0; i < this.meta.talents[id]; i++) this.meta.coins += TALENT_COSTS[i]; this.meta.talents[id] = 0; }); this.saveMeta(); this.refreshMenu(); this.openTalent(); },
  closeModal() { this.setData({ modal: emptyModal() }); },

  openReplay() { if(this.phase==='menu')this.playMusic('lobby');this.replayTab=this.replayTab||'challenge';this.setData({modal:{type:'replay',title:'轮回记录',subtitle:'难度挑战 · 每日契约 · 图鉴成就'},replayTab:this.replayTab,difficultyChoices:DIFFICULTIES.map((d,i)=>({...d,id:i+1,locked:i+1>(this.meta.unlockedDifficulty||1),selected:i+1===(this.meta.difficulty||1)})),dailyRule:this.getDailyRule(),achievements:ACHIEVEMENTS.map(a=>({...a,done:!!this.meta.achievements[a.id],claimed:!!this.meta.achievementClaimed[a.id]})),weaponBook:Object.keys(WEAPONS).map(id=>({id,name:WEAPONS[id].name,icon:WEAPONS[id].icon,tag:WEAPONS[id].tag,found:!!this.meta.discoveries.weapons[id],evolved:!!this.meta.discoveries.evolved[id]})),affixBook:Object.keys(AFFIXES).map(id=>({id,name:AFFIXES[id].name,text:AFFIXES[id].text,found:!!this.meta.discoveries.affixes[id]})),bossBook:Object.keys(BOSSES).map(id=>({id,name:BOSSES[id].name,found:!!this.meta.discoveries.bosses[id]}))}); },
  setReplayTab(e) { this.replayTab=e.currentTarget.dataset.tab;this.setData({replayTab:this.replayTab}); },
  chooseDifficulty(e) { const id=Number(e.currentTarget.dataset.id);if(id>(this.meta.unlockedDifficulty||1))return;this.meta.difficulty=id;this.saveMeta();this.openReplay(); },

  openSettings() { if(this.phase==='menu')this.playMusic('lobby');this.settingsReturn = this.phase === 'paused' ? 'pause' : 'menu'; this.setData({ settings: this.meta.settings, modal: { type: 'settings', title: '设置', subtitle: '设置会自动保存' } }); },
  closeSettings() { if (this.settingsReturn === 'pause') this.setData({ modal: { type: 'pause', title: '已暂停', subtitle: '战斗时间已停止' } }); else this.closeModal(); },
  toggleSound(e) { this.meta.settings.sound = e.detail.value; if(!e.detail.value)Object.keys(this.audioPool||{}).forEach(k=>this.audioPool[k].forEach(a=>a.stop())); this.saveMeta(); this.setData({ settings: this.meta.settings }); },
  toggleMusic(e) { this.meta.settings.music=e.detail.value;this.saveMeta();if(e.detail.value)this.playMusic(this.phase==='menu'?'lobby':this.run&&this.run.enemies.some(x=>x.bossId&&!x.dead)?'boss':'battle');else if(this.musicAudio)this.musicAudio.pause();this.setData({settings:this.meta.settings}); },
  toggleQuality(e) { this.meta.settings.lowQuality = e.detail.value; this.saveMeta(); this.setData({ settings: this.meta.settings }); },
  resetTutorial() { this.meta.settings.tutorial = true; this.saveMeta(); wx.showToast({ title: '已重置', icon: 'success' }); },

  loadCanvasImage(cache,id,path) { if(!cache[id]&&this.canvas){const img=this.canvas.createImage();img.ready=false;img.onload=()=>{img.ready=true;if(!this.destroyed&&this.run&&this.phase==='playing')this.startCanvasLoop();};img.onerror=()=>{img.ready=false;img.failed=true;};img.src=path;cache[id]=img;}return cache[id]||null; },
  startCanvasLoop() { if(!this.canvas||this.destroyed||this.frame!=null)return;this.lastTime=Date.now();this.frame=this.canvas.requestAnimationFrame(this.canvasLoop); },
  stopCanvasLoop() { if(!this.canvas||this.frame==null)return;this.canvas.cancelAnimationFrame(this.frame);this.frame=null; },

  joystickStart(e) { this.joystickMove(e); },
  joystickMove(e) {
    const t = e.touches && e.touches[0]; if (!t || !this.viewport) return;
    const cx = 22 + 52, cy = this.viewport.height - 18 - 52;
    let x = t.clientX - cx, y = t.clientY - cy; const len = Math.hypot(x, y), max = 30; if (len > max) { x *= max / len; y *= max / len; }
    this.input = { x: x / max, y: y / max }; this.setData({ stick: { x: Math.round(x), y: Math.round(y) } });
  },
  joystickEnd() { this.input = { x: 0, y: 0 }; this.setData({ stick: { x: 0, y: 0 } }); },

  stats() {
    const r = this.run, c = CHARACTERS.find(x => x.id === r.character), p = r.passives;
    const watch = r.character === 'watchman' ? Math.min(4, Math.floor(r.level / 5)) * .05 : 0;
    const daily=r.dailyRule;return { speed: c.speed * (1 + (p.speed || 0) * .06 + this.meta.talents.speed * .04) * (daily==='march'?1.12:1), damage: (1 + (p.power || 0) * .1 + this.meta.talents.damage * .05 + watch) * (1 + (r.refine || 0) * .06) * (r.time<(r.supplyPowerUntil||0)?1.25:1) * (daily==='firepower'?1.12:1), area: (r.character === 'ember' ? 1.2 : 1) * (1 + (p.area || 0) * .1), cooldown: Math.max(.5, (r.character === 'gale' ? .95 : 1) * (1 - (p.cooldown || 0) * .06)), duration: 1 + (p.duration || 0) * .12, pickup: 44 * (1 + (p.pickup || 0) * .25 + this.meta.talents.pickup * .1) };
  },

  update(dt) {
    if (!this.run || this.phase !== 'playing') return;
    const r = this.run, s = this.stats(); r.time += dt; r.invuln = Math.max(0, r.invuln - dt); r.shake = Math.max(0, r.shake - dt * 20);
    this.timeline(); this.updateHorde(dt); this.movePlayer(dt, s);this.updateCharacterSkill(dt,s);this.updateAltar(dt);this.updateHazards(dt);this.updateSupplies();
    r.spawnTimer -= dt; if (r.spawnTimer <= 0 && !r.horde) { const count = r.time > 780 ? 4 : r.time > 420 ? 3 : r.time > 180 ? 2 : 1; for (let i = 0; i < count; i++) this.spawnEnemy();r.spawnTimer = Math.max(.24,(1.1-r.time/1700)/(DIFFICULTIES[(r.difficulty||1)-1]?.spawn||1)); }
    this.updateEnemies(dt); this.updateBossBullets(dt); this.fireWeapons(dt, s); this.updateTome(dt, s); this.updateProjectiles(dt); this.updateZones(dt); this.updatePickups(dt, s);
    r.particles.forEach(p => { p.ttl -= dt;if(p.x!=null&&!p.thorns&&!p.book){p.x += (p.vx || 0) * dt;p.y += (p.vy || 0) * dt;p.vy=(p.vy||0)+90*dt;} }); r.particles = r.particles.filter(p => p.ttl > 0);
    if(r.stealAcc>0){r.stealTimer=(r.stealTimer||0)+dt;if(r.stealTimer>=.8){r.damageText.push({x:r.x,y:r.y-28,text:`+${Math.max(1,Math.round(r.stealAcc))}`,color:'#7de08a',ttl:.7});r.stealAcc=0;r.stealTimer=0;}}else r.stealTimer=0;
    r.damageText.forEach(p => { p.ttl -= dt; p.y -= 28 * dt; }); r.damageText = r.damageText.filter(p => p.ttl > 0);
    r.snapshotTimer += dt; if (r.snapshotTimer > 20) { r.snapshotTimer = 0; this.saveSnapshot(); }
    this.hudTick = (this.hudTick || 0) + dt; if (this.hudTick > .12) { this.hudTick = 0; this.syncHud(); }
  },

  movePlayer(dt, s) { const r = this.run, i = this.input || { x: 0, y: 0 }; if (i.x || i.y) { r.lastX = i.x; r.lastY = i.y; } r.x = clamp(r.x + i.x * s.speed * dt, 20, WORLD.width - 20); r.y = clamp(r.y + i.y * s.speed * dt, 20, WORLD.height - 20); },

  updateCharacterSkill(dt,s) { const r=this.run,c=CHARACTERS.find(x=>x.id===r.character);r.characterSkillCd=Math.max(0,(r.characterSkillCd||0)-dt);if(r.characterSkillCd>0)return;const cooldown=r.character==='gale'?12:16,damage=42*s.damage*(1+(r.level-1)*.035),radius=r.character==='ember'?138:105;r.characterSkillCd=cooldown;this.playSound('skill');if(r.character==='gale'){const len=Math.max(.01,Math.hypot(r.lastX,r.lastY)),dx=r.lastX/len,dy=r.lastY/len;r.x=clamp(r.x+dx*145,25,WORLD.width-25);r.y=clamp(r.y+dy*145,25,WORLD.height-25);r.invuln=Math.max(r.invuln,.28);r.enemies.forEach(e=>{const px=e.x-r.x,py=e.y-r.y,along=px*dx+py*dy,across=Math.abs(px*dy-py*dx);if(!e.dead&&along>-55&&along<105&&across<42+e.r)this.damageEnemy(e,damage,'arrow');});r.particles.push({ring:true,x:r.x,y:r.y,radius:74,ttl:.32,maxTtl:.32,color:'#8ad8ff'});}else if(r.character==='ember'){r.zones.push({type:'fire',id:'flask',x:r.x,y:r.y,radius,ttl:2.6,age:0,tick:0,damage:damage*.45});r.particles.push({ring:true,x:r.x,y:r.y,radius,ttl:.4,maxTtl:.4,color:'#ff884d'});}else{r.enemies.forEach(e=>{if(!e.dead&&distance(e,r)<radius+e.r)this.damageEnemy(e,damage,'blade');});r.particles.push({ring:true,x:r.x,y:r.y,radius,ttl:.36,maxTtl:.36,color:'#e8d3a0'});}},

  timeline() {
    const r = this.run;
    if (r.endless) { this.updateEndless(); return; }
    const warn = (key, at, text) => { if (r.time >= at && !r.warned[key]) { r.warned[key] = true; this.showToast(text, 3200); } };
    if(r.time>=75&&!r.events.supply1){r.events.supply1=true;this.spawnSupply();}if(r.time>=210&&!r.events.altar1){r.events.altar1=true;this.startAltar();}if(r.time>=520&&!r.events.supply2){r.events.supply2=true;this.spawnSupply();}
    warn('h1w',145,'怪物群潮正在集结');if(r.time>=150&&!r.events.h1){r.events.h1=true;this.startHorde(1);}
    warn('e5w', 296, '强大敌人正在接近'); warn('e5', 300, '精英敌人出现'); if (r.time >= 300 && !r.events.e5) { r.events.e5 = true; this.spawnEnemy('guard', 'elite', 'tier2'); }
    warn('h2w',445,'第二波群潮即将来袭');if(r.time>=450&&!r.events.h2){r.events.h2=true;this.startHorde(2);}
    warn('b10w', 596, '铁墓守卫正在苏醒'); warn('b10', 600, '首领 · 铁墓守卫'); if (r.time >= 600 && !r.events.b10 && !r.events.midbossDefeated) { r.events.b10 = true; this.spawnBoss('gravewarden', 'midboss'); }
    if (r.time >= 660 && !r.events.e11) { r.events.e11 = true; this.spawnEnemy('runner', 'elite'); this.spawnEnemy('thrower', 'elite'); }
    warn('h3w',745,'终局群潮正在逼近');if(r.time>=750&&!r.events.h3){r.events.h3=true;this.startHorde(3);}
    warn('b15w', 896, '深渊正在凝视这里'); warn('b15', 900, '最终首领 · 深渊监视者'); if (r.time >= RUN_SECONDS && !r.events.b15 && !r.events.finalbossDefeated) { r.events.b15 = true; this.spawnBoss('abysswatcher', 'finalboss'); }
  },

  spawnSupply() { const r=this.run,a=rnd(0,Math.PI*2),d=190;r.supplies=r.supplies||[];r.supplies.push({x:clamp(r.x+Math.cos(a)*d,45,WORLD.width-45),y:clamp(r.y+Math.sin(a)*d,45,WORLD.height-45)});this.showToast('附近发现补给残骸',2200); },
  updateSupplies() { const r=this.run,s=r.supplies||[];for(let i=s.length-1;i>=0;i--){if(distance(s[i],r)<42){s.splice(i,1);this.phase='supply';this.setData({modal:{type:'supply',title:'废墟补给',subtitle:'选择一项立即生效',choices:[{id:'heal',name:'医疗物资',text:'回复 35% 最大生命'},{id:'coin',name:'旧世钱箱',text:'获得 25 金币'},{id:'power',name:'超载电池',text:'90 秒内伤害 +25%'}]}});return;}} },
  chooseSupply(e) { const r=this.run,id=e.currentTarget.dataset.id;if(this.phase!=='supply')return;if(id==='heal')r.hp=Math.min(r.maxHp,r.hp+r.maxHp*.35);else if(id==='coin')r.coins+=25;else r.supplyPowerUntil=Math.max(r.supplyPowerUntil||0,r.time+90);this.phase='playing';this.lastTime=Date.now();this.setData({modal:emptyModal()});this.showToast(id==='heal'?'生命已恢复':id==='coin'?'获得 25 金币':'伤害提升 90 秒',1800);this.syncHud(true);this.startCanvasLoop(); },
  startAltar() { const r=this.run,a=rnd(0,Math.PI*2),d=230;r.altar={x:clamp(r.x+Math.cos(a)*d,110,WORLD.width-110),y:clamp(r.y+Math.sin(a)*d,110,WORLD.height-110),radius:92,progress:0,need:8,spawn:0,active:true};this.showToast('净化祭坛出现 · 进入光环守卫',3200); },
  updateAltar(dt) { const r=this.run,a=r.altar;if(!a||!a.active)return;const inside=distance(a,r)<a.radius;a.progress=clamp(a.progress+(inside?dt:-dt*.25),0,a.need);a.spawn-=dt;if(a.spawn<=0){a.spawn=inside?.85:1.35;this.spawnEnemy(r.time>360?(Math.random()<.5?'runner':'thrower'):'chaser');}if(a.progress>=a.need){a.active=false;r.events.altarDone=true;this.showToast('祭坛净化完成 · 获得宝箱',2200);this.openChest();} },
  updateHazards(dt) { const r=this.run,names={fissure:'火焰裂缝',poison:'腐化毒雾',storm:'废墟风暴',dark:'深渊黑暗'};(r.hazards||[]).forEach(h=>{const active=r.time>=h.start&&r.time<h.end;if(active&&!h.started){h.started=true;h.tick=0;if(h.type==='poison'){const a=rnd(0,Math.PI*2);h.x=clamp(r.x+Math.cos(a)*150,260,WORLD.width-260);h.y=clamp(r.y+Math.sin(a)*150,260,WORLD.height-260);h.radius=230;}this.showToast(`环境异变 · ${names[h.type]}`,2600);}if(!active){if(h.started&&!h.ended&&r.time>=h.end){h.ended=true;this.showToast(`${names[h.type]}已经消退`,1800);}return;}h.tick=(h.tick||0)-dt;if(h.type==='fissure'&&h.tick<=0){h.tick=4.2;const len=Math.max(.01,Math.hypot(r.lastX,r.lastY)),px=-r.lastY/len,py=r.lastX/len;[-95,0,95].forEach(offset=>r.zones.push({type:'danger',id:'hazard',hazard:'fissure',x:clamp(r.x+r.lastX/len*70+px*offset,45,WORLD.width-45),y:clamp(r.y+r.lastY/len*70+py*offset,45,WORLD.height-45),radius:48,ttl:1.45,delay:.85,age:0,hit:false,damage:r.maxHp*.1}));}else if(h.type==='poison'&&h.tick<=0){h.tick=.8;if(distance(h,r)<h.radius+14)this.hurtPlayer(r.maxHp*.055);}else if(h.type==='storm'){h.angle=(h.angle||0)+dt*.22;const dx=Math.cos(h.angle),dy=Math.sin(h.angle);r.x=clamp(r.x+dx*48*dt,20,WORLD.width-20);r.y=clamp(r.y+dy*48*dt,20,WORLD.height-20);r.enemies.forEach(e=>{if(!e.bossId){e.x=clamp(e.x+dx*28*dt,20,WORLD.width-20);e.y=clamp(e.y+dy*28*dt,20,WORLD.height-20);}});}}); },

  updateEndless() {
    const r = this.run, cycle = r.endlessCycle, ct = r.time - r.cycleStart, k = s => `ec${cycle}_${s}`;
    if (!r.events[k('h')] && ct >= 8) { r.events[k('h')] = true; this.startHorde(3); }
    if (!r.events[k('e')] && ct >= 60) { r.events[k('e')] = true; this.showToast('无尽精英出现', 2000); this.spawnEnemy('guard', 'elite', 'endless'); this.spawnEnemy('summoner', 'elite', 'endless'); }
    if (!r.events[k('b')] && ct >= 110) { r.events[k('b')] = true; const bossId = cycle % 2 === 1 ? 'abysswatcher' : 'gravewarden'; this.spawnBoss(bossId, 'endlessboss', 1.2 + (cycle - 1) * .45); this.showToast(`无尽首领 · ${BOSSES[bossId].name}`, 2600); }
    if (ct >= 150) { r.endlessCycle = cycle + 1; r.cycleStart = r.time; this.showToast(`无尽轮回 · 第 ${r.endlessCycle} 层 · 敌人更强了`, 3000); this.vibrate('medium'); }
  },

  offerEndless() {
    this.saveSnapshot(); this.phase = 'endless'; this.vibrate('heavy');
    this.setData({ modal: { type: 'endless', title: '胜利 · 废墟幸存者', subtitle: '最终首领已被击败，是时候做出抉择' } });
  },
  continueEndless() {
    const r = this.run; if (!r || this.phase !== 'endless') return;
    r.endless = true; r.endlessCycle = 1; r.cycleStart = r.time; this.phase = 'playing'; this.lastTime = Date.now();
    this.setData({ modal: emptyModal() }); this.saveSnapshot(); this.startCanvasLoop();
    this.showToast('无尽轮回 · 第 1 层 · 敌人正在聚集', 3200); this.vibrate('heavy'); this.syncHud(true);
  },
  claimVictory() { if (this.phase !== 'endless') return; this.finishRun('win'); },

  startHorde(wave) {
    const settings={1:{total:36,duration:11,types:['chaser','runner'],reward:12},2:{total:60,duration:15,types:['chaser','runner','thrower','guard'],reward:22},3:{total:88,duration:19,types:['runner','thrower','guard','bomber','summoner'],reward:35}}[wave];if(!settings||this.run.horde)return;
    this.run.horde={wave,total:settings.total,remaining:settings.total,interval:settings.duration/settings.total,timer:0,types:settings.types,reward:settings.reward,spawned:0};this.showToast(this.run.endless?`第 ${this.run.endlessCycle} 层群潮来袭`:`第 ${wave} 波群潮来袭`,2600);this.vibrate('heavy');
  },

  updateHorde(dt) {
    const r=this.run,h=r.horde;if(!h)return;h.timer-=dt;let guard=0;while(h.remaining>0&&h.timer<=0&&guard++<8){if(r.enemies.length<230){this.spawnHordeUnit(h);h.remaining--;h.spawned++;}h.timer+=h.interval;}
    if(h.remaining===0&&!r.enemies.some(e=>e.hordeWave===h.wave&&!e.dead)){const reward=Math.round(h.reward*(r.dailyRule==='salvage'?1.5:1));r.coins+=reward;this.showToast(`群潮肃清 · 获得 ${reward} 金币`,2600);r.horde=null;this.syncHud(true);}
  },

  spawnHordeUnit(h) {
    const r=this.run,type=h.types[h.spawned%h.types.length],d=ENEMIES[type],side=h.wave===1?h.spawned%2:h.spawned%4,a=[0,Math.PI,Math.PI/2,-Math.PI/2][side]+rnd(-.22,.22),radius=Math.max(this.viewport?this.viewport.width:700,520)*.68,scale=(1+Math.floor(r.time/300)*.34)*(DIFFICULTIES[(r.difficulty||1)-1]?.hp||1),em=r.endless?1+(r.endlessCycle-1)*.15:1;
    r.enemies.push({id:++r.id,type,hordeWave:h.wave,x:clamp(r.x+Math.cos(a)*radius,25,WORLD.width-25),y:clamp(r.y+Math.sin(a)*radius,25,WORLD.height-25),hp:d.hp*scale*em,maxHp:d.hp*scale*em,r:d.r,speed:d.speed*1.1,damage:d.damage*(1+(h.wave-1)*.15)*em*(DIFFICULTIES[(r.difficulty||1)-1]?.damage||1),attack:2,warning:0,slow:0,dead:false});
  },

  spawnBoss(bossId, special, hpMul) {
    const r=this.run,d=BOSSES[bossId],mul=hpMul||1;if(!d||r.enemies.some(e=>e.bossId===bossId&&!e.dead))return;
    const a=rnd(0,Math.PI*2),radius=Math.max(this.viewport?this.viewport.width:700,500)*.62;
    const difficulty=DIFFICULTIES[(r.difficulty||1)-1]||DIFFICULTIES[0],stageMul=(r.difficulty||1)>=4?1.16:1;
    this.playMusic('boss');this.playSound('boss_alert');r.enemies.push({id:++r.id,type:d.baseType,bossId,special,x:clamp(r.x+Math.cos(a)*radius,70,WORLD.width-70),y:clamp(r.y+Math.sin(a)*radius,70,WORLD.height-70),hp:d.hp*mul*difficulty.hp,maxHp:d.hp*mul*difficulty.hp,r:d.r,speed:d.speed,damage:d.damage*difficulty.damage*stageMul,attack:1.8,skill:0,phase:1,warning:0,slow:0,dead:false});
  },

  pickAffix(tier,type,exclude=[]) { const pool=Object.keys(AFFIXES).filter(id=>AFFIXES[id].tier===tier&&!exclude.includes(id)&&!(type==='bomber'&&(id==='corpse'||id==='split'))&&(!(id==='teleport')||['thrower','summoner','guard'].includes(type)));return pool.length?pool[Math.floor(Math.random()*pool.length)]:''; },

  showAffixTutorial(id) { const r=this.run,key=`affixTip_${id}`;if(!id||r.events[key])return;r.events[key]=true;this.affixToastQueue=this.affixToastQueue||[];this.affixToastQueue.push(AFFIXES[id].text);if(this.affixToastQueue.length>1)return;const next=()=>{if(!this.affixToastQueue.length)return;this.showToast(this.affixToastQueue[0],2400);setTimeout(()=>{this.affixToastQueue.shift();if(this.affixToastQueue.length)next();},2500);};next(); },

  assignAffixes(e,mode) { const r=this.run,active=r.enemies.filter(x=>x.affix&&!x.dead);if(active.length>=4){if(!mode)return;const old=active.find(x=>!x.special)||active[0];old.affix='';old.affix2='';old.shield=0;old.maxShield=0;}let ids=[];if(mode==='tier2')ids=[this.pickAffix(2,e.type)];else if(mode==='endless'){const tier=Math.random()<.5?1:2,first=this.pickAffix(tier,e.type)||this.pickAffix(tier===1?2:1,e.type);ids=[first];if(r.endlessCycle>=3&&Math.random()<.3){const tier2=Math.random()<.5?1:2,second=this.pickAffix(tier2,e.type,ids)||this.pickAffix(tier2===1?2:1,e.type,ids);if(second)ids.push(second);}}else{const time=r.time+((r.difficulty||1)>=3?120:0);if(time<180)return;if(e.special==='elite'&&(r.difficulty||1)>=5)ids=[this.pickAffix(2,e.type)||this.pickAffix(1,e.type)];else if(e.special)return;else{const roll=Math.random(),tier=time<300?(roll<.08?1:0):time<600?(roll<.12?1:roll<.16?2:0):(roll<.15?1:roll<.23?2:0);if(tier)ids=[this.pickAffix(tier,e.type)];}}if((r.difficulty||1)>=5&&e.special==='elite'&&ids.length===1){const second=this.pickAffix(2,e.type,ids)||this.pickAffix(1,e.type,ids);if(second)ids.push(second);}ids=ids.filter(Boolean);if(!ids.length)return;e.affix=ids[0];e.affix2=ids[1]||'';if(ids.includes('shield')){e.maxShield=e.maxHp*.4;e.shield=e.maxShield;}if(ids.includes('teleport'))e.tpCd=4;if(ids.includes('healer'))e.healCd=1;ids.forEach(id=>this.showAffixTutorial(id)); },

  spawnEnemy(type, special, affixMode) {
    const r = this.run; if (r.enemies.length >= 250 && !special) return;
    const available = Object.keys(ENEMIES).filter(id => ENEMIES[id].from <= r.time); type = type || available[Math.floor(Math.random() * available.length)];
    const d = ENEMIES[type], a = rnd(0, Math.PI * 2), radius = Math.max(this.viewport ? this.viewport.width : 700, 500) * .7;
    const boss = special === 'midboss' || special === 'finalboss', em = r.endless ? 1 + (r.endlessCycle - 1) * .15 : 1,diff=DIFFICULTIES[(r.difficulty||1)-1]||DIFFICULTIES[0], maxHp = (boss ? (special === 'finalboss' ? 4800 : 2500) : d.hp * (1 + Math.floor(r.time / 300) * .45) * (special === 'elite' ? 7 : 1))*em*diff.hp;
    const enemy={ id: ++r.id, type, special, x: clamp(r.x + Math.cos(a) * radius, 30, WORLD.width - 30), y: clamp(r.y + Math.sin(a) * radius, 30, WORLD.height - 30), hp: maxHp, maxHp, r: boss ? 42 : special === 'elite' ? d.r * 1.6 : d.r, speed: d.speed, damage: d.damage * (boss ? 1.6 : special === 'elite' ? 1.3 : 1) * em*diff.damage*((r.difficulty||1)>=4&&boss?1.16:1), attack: rnd(1.5, 3), warning: 0, slow: 0, dead: false };r.enemies.push(enemy);this.assignAffixes(enemy,affixMode);
  },

  updateEnemies(dt) {
    const r = this.run;
    r.enemies.forEach(e=>{e.healLock=Math.max(0,(e.healLock||0)-dt);});
    for (const e of r.enemies) {
      if (e.dead) continue; const enemyData=ENEMIES[e.type],ranged=!e.bossId&&enemyData.shot,d=Math.max(1,distance(e,r)),dx=(r.x-e.x)/d,dy=(r.y-e.y)/d;e.attack-=dt;e.slow=hasAffix(e,'shield')&&e.shield>0?0:Math.max(0,e.slow-dt);if(e.poisonUntil>r.time){this.damageEnemy(e,(e.poisonDps||0)*dt,'plague');if(e.dead)continue;}else if(e.poisonUntil){e.poisonUntil=0;e.poisonDps=0;}
      if(hasAffix(e,'healer')){e.healCd=(e.healCd||1)-dt;if(e.healCd<=0){e.healCd+=1;r.enemies.forEach(t=>{if(!t.dead&&(t.healLock||0)<=0&&distance(e,t)<=90){t.hp=Math.min(t.maxHp,t.hp+t.maxHp*.02);t.healLock=1;}});}}
      if(hasAffix(e,'teleport')){e.tpCd=(e.tpCd==null?4:e.tpCd)-dt;if(e.tpCd<=0&&d>300){const ox=e.x,oy=e.y;e.x=clamp(e.x+dx*260,25,WORLD.width-25);e.y=clamp(e.y+dy*260,25,WORLD.height-25);e.tpCd=4;for(let i=0;i<6;i++){r.particles.push({x:ox,y:oy,vx:rnd(-90,90),vy:rnd(-90,30),radius:rnd(2,5),ttl:rnd(.25,.5),color:'#bd72ff'});r.particles.push({x:e.x,y:e.y,vx:rnd(-70,70),vy:rnd(-100,20),radius:rnd(2,5),ttl:rnd(.25,.5),color:'#bd72ff'});}}}
      if(e.shootWindup>0){e.shootWindup-=dt;if(e.shootWindup<=0){e.shootWindup=0;this.fireEnemyShot(e,dx,dy);e.attack=enemyData.shotCooldown*rnd(.9,1.1);}}else if(ranged&&e.attack<=0&&d<enemyData.shotRange){e.shootWindup=.42;e.warning=.42;}
      if ((r.time>=r.freezeUntil&&r.time>=(e.frozenUntil||0))||e.special) { const speed=e.speed*(hasAffix(e,'swift')?1.55:1)*(e.slow?.48:1),move=ranged?(d<190?-1:d>enemyData.shotRange*.68?1:0):1;if(!e.shootWindup){e.x+=dx*speed*move*dt;e.y+=dy*speed*move*dt;} }
      if (e.bossId && e.attack <= 0) this.useBossSkill(e);
      e.warning = Math.max(0, e.warning - dt);
      if (d < e.r + 15) this.hurtPlayer(e.damage);
    }
    r.enemies = r.enemies.filter(e => !e.dead);
  },

  fireEnemyShot(e,dx,dy) {
    const r=this.run,d=ENEMIES[e.type],base=Math.atan2(dy,dx),angles=d.shot==='void'?[-.18,0,.18]:[0];
    angles.forEach(offset=>{const a=base+offset;r.bullets.push({kind:d.shot,x:e.x+Math.cos(a)*(e.r+8),y:e.y+Math.sin(a)*(e.r+8),vx:Math.cos(a)*d.shotSpeed,vy:Math.sin(a)*d.shotSpeed,r:d.shot==='void'?7:6,ttl:d.shot==='void'?4:3.2,damage:e.damage*(d.shot==='void'?.5:.7),dead:false});});
  },

  useBossSkill(e) {
    const r=this.run,d=BOSSES[e.bossId],stage=e.hp<=e.maxHp*.25?3:e.hp<=e.maxHp*.6?2:1;if(stage>(e.phase||1)){e.phase=stage;r.particles.push({ring:true,x:e.x,y:e.y,radius:e.r*(stage===3?4:3),ttl:.65,maxTtl:.65,color:stage===3?'#ff5d57':'#d59bff'});r.shake=Math.max(r.shake,6);this.showToast(stage===3?`${d.name}进入狂暴阶段`:`${d.name}改变了战斗场地`,2200);}e.phase=stage;e.skill=(e.skill||0)+1;e.warning=.9;this.playSound('boss_attack');
    if(e.bossId==='gravewarden'){
      if(e.skill%2){const count=stage,base=rnd(0,Math.PI*2);for(let i=0;i<count;i++){const a=base+i*Math.PI*2/count,rr=i?85:0,delay=.78+i*.1;r.zones.push({type:'danger',id:'boss',effect:'gravewarden',x:clamp(r.x+Math.cos(a)*rr,45,WORLD.width-45),y:clamp(r.y+Math.sin(a)*rr,45,WORLD.height-45),radius:stage===3?82:96,ttl:delay+.55,delay,age:0,hit:false,damage:e.damage*(stage===3?1.3:1.15)});}this.showToast(stage===1?'铁墓重击 · 离开红圈':'铁墓连震 · 寻找空隙',1200);}
      else if(stage<3){this.spawnMinions(e,stage===2?'runner':'chaser',3);this.showToast('铁墓守卫召唤亡卒',1200);}else{this.spawnBulletRing(e,14,185);this.showToast('铁墓狂震 · 环形冲击',1100);}
      e.attack=stage===3?1.35:stage===2?2.1:3.1;
    }else{
      if(e.skill%2){const count=stage===3?7:stage===2?5:3;for(let i=0;i<count;i++){const a=i*Math.PI*2/count+r.time,rr=i?rnd(55,stage===3?190:150):0,delay=.68+i*.07;r.zones.push({type:'danger',id:'boss',effect:'abysswatcher',x:clamp(r.x+Math.cos(a)*rr,40,WORLD.width-40),y:clamp(r.y+Math.sin(a)*rr,40,WORLD.height-40),radius:stage===1?62:68,ttl:delay+.55,delay,age:0,hit:false,damage:e.damage*(stage===3?1.2:1)});}this.showToast(stage===3?'深渊吞噬 · 七重凝视':'深渊凝视 · 连续预警',1300);}
      else{this.spawnBulletRing(e,stage===3?22:stage===2?16:10,stage===3?215:stage===2?185:155);this.showToast(stage===3?'深渊狂暴弹幕':'深渊弹幕',1000);}
      e.attack=stage===3?1.2:stage===2?1.65:2.55;
    }
  },

  spawnMinions(boss,type,count) {
    const r=this.run,d=ENEMIES[type];for(let i=0;i<count;i++){const a=i*Math.PI*2/count+r.time,x=clamp(boss.x+Math.cos(a)*75,25,WORLD.width-25),y=clamp(boss.y+Math.sin(a)*75,25,WORLD.height-25);r.enemies.push({id:++r.id,type,x,y,hp:d.hp*2,maxHp:d.hp*2,r:d.r,speed:d.speed*1.08,damage:d.damage,attack:2,warning:0,slow:0,dead:false});}
  },

  spawnBulletRing(boss,count,speed) {
    const r=this.run;for(let i=0;i<count;i++){const a=i*Math.PI*2/count+r.time*.35;r.bullets.push({x:boss.x,y:boss.y,vx:Math.cos(a)*speed,vy:Math.sin(a)*speed,r:7,ttl:4,damage:boss.damage*.7,dead:false});}
  },

  updateBossBullets(dt) {
    const r=this.run;for(const b of r.bullets){b.ttl-=dt;b.x+=b.vx*dt;b.y+=b.vy*dt;if(distance(b,r)<b.r+13){this.hurtPlayer(b.damage);b.dead=true;}}
    r.bullets=r.bullets.filter(b=>!b.dead&&b.ttl>0&&b.x>0&&b.y>0&&b.x<WORLD.width&&b.y<WORLD.height);
  },

  spawnLightningArc(x1,y1,x2,y2) {
    const count=this.meta.settings.lowQuality?5:9,points=[];for(let i=0;i<=count;i++){const t=i/count,fade=Math.sin(Math.PI*t),nx=-(y2-y1),ny=x2-x1,len=Math.max(1,Math.hypot(nx,ny)),j=i===0||i===count?0:rnd(-12,12)*fade;points.push({x:x1+(x2-x1)*t+nx/len*j,y:y1+(y2-y1)*t+ny/len*j});}
    this.run.particles.push({lightning:true,points,ttl:.2,maxTtl:.2,color:'#8fdcff'});
    this.run.particles.push({x:x2,y:y2,vx:0,vy:0,radius:11,ttl:.18,color:'#d9f7ff',flash:true});this.run.particles.push({skillEffect:'lightning',x:x2,y:y2,ttl:.42,maxTtl:.42,effectSize:84});
  },

  nearest(max = Infinity, from) { const r = this.run, o = from || r; let best = null, bd = max; r.enemies.forEach(e => { const d = distance(e, o); if (!e.dead && d < bd) { best = e; bd = d; } }); return best; },

  updateTome(dt,s) { const r=this.run,level=r.weapons.tome||0;if(!level||!r.tome||!r.tome.on)return;const evolved=r.evolved.includes('tome'),count=2+Math.floor(level/2)+(evolved?2:0),radius=95*s.area,damage=WEAPONS.tome.damage*s.damage*(1+(level-1)*.24)*(evolved?1.55:1),trail=!this.meta.settings.lowQuality&&((r.tomeTrail||0)+dt>=.05);r.tomeAngle=(r.tomeAngle||0)+(2.2+level*.15+(evolved?.8:0))*dt;r.tomeTrail=trail?0:(r.tomeTrail||0)+dt;r.tome.cd=r.tome.cd||{};for(let i=0;i<count;i++){const a=r.tomeAngle+i*Math.PI*2/count,x=r.x+Math.cos(a)*radius,y=r.y+Math.sin(a)*radius;r.enemies.forEach(e=>{const key=`${i}:${e.id}`,last=r.tome.cd[key]==null?-99:r.tome.cd[key];if(!e.dead&&Math.hypot(e.x-x,e.y-y)<18+e.r&&r.time-last>=.45){r.tome.cd[key]=r.time;e.tomeMarkedUntil=r.time+1.2;this.damageEnemy(e,damage,'tome');}});if(trail)r.particles.push({book:true,x,y,radius:5,ttl:.12,maxTtl:.12,color:WEAPONS.tome.color});}if((r.tomeCleanAt||0)<r.time){r.tomeCleanAt=r.time+2;Object.keys(r.tome.cd).forEach(k=>{if(r.time-r.tome.cd[k]>1)delete r.tome.cd[k];});} },

  fireWeapons(dt, s) {
    const r = this.run,duration=s.duration||1;
    Object.keys(r.weapons).forEach(id => {
      const level = r.weapons[id], w = WEAPONS[id]; r.timers[id] = (r.timers[id] || 0) - dt; if (r.timers[id] > 0) return;
      const target = this.nearest(620); if (!target && !['ring','frost','totem','tome','shield'].includes(id)) return;
      const evolved = r.evolved.includes(id), damage = w.damage * s.damage * (1 + (level - 1) * .24) * (evolved ? 1.55 : 1); r.timers[id] = Math.max(.14, w.cooldown * s.cooldown * (1 - (level - 1) * .08) * (evolved ? .82 : 1));
      if (['blade','arrow','raven'].includes(id)) { const angle = id === 'arrow' ? Math.atan2(r.lastY,r.lastX) : Math.atan2(target.y-r.y,target.x-r.x); const count = evolved && id !== 'raven' ? 2 : 1; for(let i=0;i<count;i++){const a=angle+(count===2?(i ? .18 : -.18):0),p={id,x:r.x,y:r.y,vx:Math.cos(a)*430,vy:Math.sin(a)*430,r:id==='blade'?12:7,damage,ttl:id==='blade'?1.2:1.5,age:0,pierce:2+Math.floor(level/2),hits:{}};if(id==='blade')Object.assign(p,{boomerang:true,startX:r.x,startY:r.y,dirX:Math.cos(a),dirY:Math.sin(a),curve:(count===2?(i?1:-1):(r.id%2?1:-1))*82,range:310,duration:1.2});r.projectiles.push(p);} }
      else if (id === 'flask') r.zones.push({ type: 'fire', id, x: target.x, y: target.y, radius: (62+level*8)*s.area, ttl: 3*duration, age: 0, tick: 0, damage });
      else if (id === 'lightning') { const hits=[...r.enemies].filter(e=>!e.dead).sort((a,b)=>distance(a,r)-distance(b,r)).slice(0,evolved?5:1+Math.floor(level/2));let from={x:r.x,y:r.y};hits.forEach(e=>{this.damageEnemy(e,damage,id);this.spawnLightningArc(from.x,from.y,e.x,e.y);from=e;});if(hits.length)r.shake=Math.max(r.shake,2.5); }
      else if (id === 'ring') { const radius=(72+level*6)*s.area; r.enemies.forEach(e=>{if(Math.abs(distance(e,r)-radius)<e.r+14)this.damageEnemy(e,damage,id);}); }
      else if (id === 'frost') { const radius=(125+level*9)*s.area;r.enemies.forEach(e=>{if(distance(e,r)<radius+e.r){this.damageEnemy(e,damage,id);if(!(hasAffix(e,'shield')&&e.shield>0))e.slow=2.2*duration;}});r.particles.push({skillEffect:'frost',x:r.x,y:r.y,radius,ttl:.42,maxTtl:.42,effectSize:radius*2.15,color:w.color}); }
      else if (id === 'beam') { const a=Math.atan2(target.y-r.y,target.x-r.x),dx=Math.cos(a),dy=Math.sin(a);r.enemies.forEach(e=>{const px=e.x-r.x,py=e.y-r.y,along=px*dx+py*dy,across=Math.abs(px*dy-py*dx);if(along>0&&along<620&&across<22+e.r)this.damageEnemy(e,damage,id);});r.particles.push({thorns:true,skillEffect:'beam',x:r.x+dx*310,y:r.y+dy*310,angle:a,length:620,effectSize:620,effectHeight:145,ttl:.55,maxTtl:.55,color:w.color}); }
      else if (id === 'totem') { const count=level>=3?2:1,len=Math.max(.001,Math.hypot(r.lastX,r.lastY)),px=-r.lastY/len,py=r.lastX/len;r.zones=r.zones.filter(z=>z.type!=='totem');for(let i=0;i<count;i++){const offset=(i-(count-1)/2)*60;r.zones.push({type:'totem',id,x:r.x+px*offset,y:r.y+py*offset,ttl:8+level*.8,age:0,tick:0,damage,range:evolved?300:240,double:evolved});} }
      else if (id === 'tome') { r.tome=r.tome||{on:false,cd:{}};r.tome.on=true;r.tome.cd=r.tome.cd||{}; }
      else if (id === 'plague') r.zones.push({type:'poison',id,x:target.x,y:target.y,radius:(70+level*6)*s.area,ttl:(2.5+level*.3)*duration,age:0,tick:0,damage,duration:(2.5+level*.3)*duration,evolved});
      else if (id === 'gravity') r.zones.push({type:'gravity',id,x:target.x,y:target.y,radius:(120+level*10)*s.area*(evolved?1.35:1),ttl:1.5,age:0,delay:1.1,hit:false,damage,pull:evolved?170:130,evolved});
      else if (id === 'spike') { const base=Math.atan2(target.y-r.y,target.x-r.x),angles=evolved?[-.25,0,.25]:[0];angles.forEach(offset=>{const a=base+offset;r.projectiles.push({id,x:r.x,y:r.y,vx:Math.cos(a)*380,vy:Math.sin(a)*380,r:9,damage,ttl:1.4,age:0,pierce:3+Math.floor(level/2),hits:{},freeze:(evolved?1.6:1.2)*duration});}); }
      else if (id === 'shield') { r.shieldUp=true;r.timers.shield=1e9; }
    });
  },

  updateProjectiles(dt) { const r=this.run;for(const p of r.projectiles){p.age=(p.age||0)+dt;if(p.boomerang){const oldX=p.x,oldY=p.y,out=.56,turn=.34,px=-p.dirY,py=p.dirX;if(p.age<=out){const t=clamp(p.age/out,0,1),u=1-t,x0=p.startX,y0=p.startY,x1=x0+p.dirX*p.range*.52+px*p.curve,y1=y0+p.dirY*p.range*.52+py*p.curve,x2=x0+p.dirX*p.range,y2=y0+p.dirY*p.range;p.x=u*u*x0+2*u*t*x1+t*t*x2;p.y=u*u*y0+2*u*t*y1+t*t*y2;p.returning=false;}else{if(!p.returning){const dx=r.x-p.x,dy=r.y-p.y,len=Math.max(1,Math.hypot(dx,dy)),speed=Math.max(1,Math.hypot(p.vx,p.vy));p.returning=true;p.returnStartX=p.x;p.returnStartY=p.y;p.returnDirX=dx/len;p.returnDirY=dy/len;p.returnControl1X=p.x+p.vx/speed*110;p.returnControl1Y=p.y+p.vy/speed*110;p.returnEndX=p.x+p.returnDirX*220;p.returnEndY=p.y+p.returnDirY*220;p.returnControl2X=p.returnEndX-p.returnDirX*90;p.returnControl2Y=p.returnEndY-p.returnDirY*90;p.ttl=5;}const rt=p.age-out;if(rt<=turn){const t=clamp(rt/turn,0,1),u=1-t;p.x=u*u*u*p.returnStartX+3*u*u*t*p.returnControl1X+3*u*t*t*p.returnControl2X+t*t*t*p.returnEndX;p.y=u*u*u*p.returnStartY+3*u*u*t*p.returnControl1Y+3*u*t*t*p.returnControl2Y+t*t*t*p.returnEndY;}else{const travel=(rt-turn)*620;p.x=p.returnEndX+p.returnDirX*travel;p.y=p.returnEndY+p.returnDirY*travel;}p.ttl-=dt;const view=this.viewport||{width:1000,height:600},camX=clamp(r.x-view.width/2,0,WORLD.width-view.width),camY=clamp(r.y-view.height/2,0,WORLD.height-view.height),margin=80;if(rt>turn&&(p.x<camX-margin||p.x>camX+view.width+margin||p.y<camY-margin||p.y>camY+view.height+margin))p.ttl=0;}p.vx=(p.x-oldX)/Math.max(dt,.001);p.vy=(p.y-oldY)/Math.max(dt,.001);}else{p.ttl-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;}for(const e of r.enemies){const hitKey=p.boomerang?`${e.id}:${p.returning?'back':'out'}`:e.id;if(!p.hits[hitKey]&&distance(p,e)<p.r+e.r){p.hits[hitKey]=1;const frozen=p.id==='spike'&&r.time<(e.frozenUntil||0),crit=this.damageEnemy(e,p.damage,p.id);if(crit&&p.id==='blade'&&!p.returning){p.range+=70;p.ttl+=.16;}if(frozen){r.enemies.forEach(t=>{if(t!==e&&!t.dead&&distance(e,t)<70+t.r)this.damageEnemy(t,p.damage*.45,'spike');});r.particles.push({ring:true,x:e.x,y:e.y,radius:70,ttl:.28,maxTtl:.28,color:'#bceeff'});}if(p.freeze&&!e.special&&!e.dead)e.frozenUntil=r.time+p.freeze;if(!p.boomerang&&p.pierce--<=0){p.ttl=0;break;}}}}r.projectiles=r.projectiles.filter(p=>p.ttl>0); },
  applyPoison(e,dps,duration,scaled) { const r=this.run;if(!e||e.dead)return;duration*=scaled?1:this.stats().duration;e.poisonUntil=r.time+duration;e.poisonDuration=duration;e.poisonDps=Math.max(e.poisonDps||0,dps); },

  updateZones(dt) { const r=this.run;for(const z of r.zones){z.ttl-=dt;z.age=(z.age||0)+dt;if(z.type==='danger'){z.delay=(z.delay==null ? .75 : z.delay)-dt;if(z.delay<=0&&!z.hit){z.hit=true;z.hitAt=z.age;if(distance(z,r)<z.radius+14)this.hurtPlayer(z.damage);r.shake=Math.max(r.shake,5);for(let i=0;i<8;i++)r.particles.push({x:z.x,y:z.y,vx:rnd(-100,100),vy:rnd(-120,10),radius:rnd(2,5),ttl:rnd(.3,.6),color:'#d9555f'});}}else if(z.type==='totem'){z.tick-=dt;if(z.tick<=0){const target=this.nearest(z.range,z);if(target){const base=Math.atan2(target.y-z.y,target.x-z.x),angles=z.double?[-.1,.1]:[0];if((target.tomeMarkedUntil||0)>r.time)angles.push(z.double?0:.12);angles.forEach(offset=>{const a=base+offset;r.projectiles.push({id:'totem',x:z.x,y:z.y-16,vx:Math.cos(a)*420,vy:Math.sin(a)*420,r:5,damage:z.damage,ttl:1.2,age:0,pierce:1,hits:{}});});z.tick=.55;}else z.tick=.3;}}else if(z.type==='gravity'){z.delay-=dt;if(z.delay>0){r.enemies.forEach(e=>{const d=Math.max(1,distance(z,e));if(!e.dead&&!e.bossId&&d<z.radius){e.x+=(z.x-e.x)/d*z.pull*dt;e.y+=(z.y-e.y)/d*z.pull*dt;}});}else if(!z.hit){z.hit=true;z.hitAt=z.age;r.enemies.forEach(e=>{const d=Math.max(1,distance(z,e));if(!e.dead&&d<z.radius+e.r){if(e.poisonUntil>r.time)this.damageEnemy(e,e.poisonDps||0,'plague');if(!e.dead)this.damageEnemy(e,z.damage,'gravity');if(z.evolved&&!e.dead&&!e.bossId){e.x=clamp(e.x+(e.x-z.x)/d*60,20,WORLD.width-20);e.y=clamp(e.y+(e.y-z.y)/d*60,20,WORLD.height-20);}}});r.particles.push({ring:true,x:z.x,y:z.y,radius:z.radius,ttl:.4,maxTtl:.4,color:WEAPONS.gravity.color});r.shake=Math.max(r.shake,4);}}else if(z.type==='poison'){z.tick-=dt;if(z.tick<=0){z.tick=.5;r.enemies.forEach(e=>{if(!e.dead&&distance(z,e)<z.radius+e.r)this.applyPoison(e,z.damage,z.duration,true);});}}else if(z.type==='fire'){z.tick-=dt;if(z.tick<=0){z.tick=.35;r.enemies.forEach(e=>{if(!e.dead&&distance(z,e)<z.radius+e.r){this.damageEnemy(e,z.damage,z.id);if(!e.dead&&e.poisonUntil>r.time&&(e.combustAt||0)<=r.time){e.combustAt=r.time+.8;r.enemies.forEach(t=>{if(!t.dead&&t!==e&&distance(e,t)<45+t.r)this.damageEnemy(t,z.damage*.35,'flask');});r.particles.push({ring:true,x:e.x,y:e.y,radius:45,ttl:.25,maxTtl:.25,color:'#d9b44a'});}}});}}else{z.tick-=dt;if(z.tick<=0){z.tick=.35;r.enemies.forEach(e=>{if(distance(z,e)<z.radius+e.r)this.damageEnemy(e,z.damage,z.id);});}}}r.zones=r.zones.filter(z=>z.ttl>0); },

  damageEnemy(e, amount, weapon) {
    if (!e || e.dead) return false;const r=this.run,cl=r.passives.crit||0,crit=cl&&Math.random()<.05+.06*cl;amount*=crit?2.5:1;const raw=amount;if(e.shield>0){const absorbed=Math.min(e.shield,amount);e.shield-=absorbed;amount-=absorbed;}if(amount>0)e.hp-=amount;
    const canText=weapon!=='plague'||(e.poisonTextAt||0)<=r.time;if(canText&&Math.random()<.35){r.damageText.push({x:e.x+rnd(-5,5),y:e.y-e.r,text:weapon==='plague'?Math.max(1,Math.round(raw)):Math.round(raw),color:crit?'#ffd257':e.shield>0?'#6fc5ff':(WEAPONS[weapon]&&WEAPONS[weapon].color)||'#fff',ttl:.5});if(weapon==='plague')e.poisonTextAt=r.time+.5;}
    if(e.hp<=0){e.dead=true;r.kills++;const sl=r.passives.steal||0;if(sl){const heal=(.3+.3*sl)*(e.bossId||e.special?10:1),before=r.hp;r.hp=Math.min(r.maxHp,r.hp+heal);r.stealAcc=(r.stealAcc||0)+r.hp-before;}if(e.poisonUntil>r.time){const radius=r.evolved.includes('plague')?130:90,count=r.evolved.includes('plague')?5:3;[...r.enemies].filter(t=>t!==e&&!t.dead&&!(t.poisonUntil>r.time)&&distance(e,t)<=radius).sort((a,b)=>distance(e,a)-distance(e,b)).slice(0,count).forEach(t=>this.applyPoison(t,e.poisonDps||0,e.poisonDuration||2.5,true));}const d=e.bossId?BOSSES[e.bossId]:ENEMIES[e.type],affixed=!!(e.affix||e.affix2),xpMul=Math.max(e.special&&!e.bossId?5:1,affixed?3:1),lk=r.passives.luck||0;r.pickups.push({type:'xp',x:e.x,y:e.y,value:d.xp*xpMul*(r.dailyRule==='bounty'&&(e.bossId||e.special)?1.5:1)});if(Math.random()<.08*Math.min(3,1+.25*lk)||e.bossId)r.pickups.push({type:'coin',x:e.x+8,y:e.y,value:Math.round((e.bossId?12:affixed?5:1)*(r.dailyRule==='salvage'?1.5:1)*(r.dailyRule==='bounty'&&(e.bossId||e.special)?1.5:1))});if(Math.random()<.015*Math.min(3,1+.35*lk))r.pickups.push({type:'potion',x:e.x-9,y:e.y+5});let metaDirty=false;if(e.bossId){if(!this.meta.discoveries.bosses[e.bossId]){this.meta.discoveries.bosses[e.bossId]=true;metaDirty=true;}r.events[`defeated_${e.bossId}`]=true;}[e.affix,e.affix2].filter(Boolean).forEach(id=>{if(!this.meta.discoveries.affixes[id]){this.meta.discoveries.affixes[id]=true;metaDirty=true;}if(!this.meta.affixRewards[id]){this.meta.affixRewards[id]=true;this.meta.coins+=10;metaDirty=true;this.showToast(`首次记录词缀 · ${AFFIXES[id].name} · +10 金币`,2200);}});if(metaDirty)this.saveMeta();if(e.special||(affixed&&Math.random()<.2*Math.min(3,1+.3*lk)))r.pickups.push({type:'chest',x:e.x,y:e.y});if(hasAffix(e,'corpse'))r.zones.push({type:'danger',id:'corpse',x:e.x,y:e.y,radius:70,ttl:1.35,delay:.8,age:0,hit:false,damage:e.damage*.5});if(hasAffix(e,'split')&&!e.split){for(let i=0;i<2;i++){const a=i?Math.PI*.2:-Math.PI*.2,maxHp=e.maxHp*.35;r.enemies.push({id:++r.id,type:e.type,split:true,x:clamp(e.x+Math.cos(a)*e.r,20,WORLD.width-20),y:clamp(e.y+Math.sin(a)*e.r,20,WORLD.height-20),hp:maxHp,maxHp,r:Math.max(7,e.r*.72),speed:e.speed*1.08,damage:e.damage*.7,attack:rnd(1.2,2.4),warning:0,slow:0,dead:false});}}const particles=this.meta.settings.lowQuality?2:e.bossId?18:5;for(let i=0;i<particles;i++)r.particles.push({x:e.x,y:e.y,vx:rnd(-100,100),vy:rnd(-130,20),radius:rnd(2,6),ttl:rnd(.35,.8),color:d.color});if(e.bossId){this.playSound('victory');if(!r.enemies.some(t=>t!==e&&t.bossId&&!t.dead))this.playMusic('battle');}if(e.special==='midboss')r.events.midbossDefeated=true;if(e.special==='finalboss'){r.events.finalbossDefeated=true;this.offerEndless();}else if(e.special==='endlessboss'){const reward=Math.round((20+r.endlessCycle*5)*(r.dailyRule==='bounty'?1.5:1)*(r.dailyRule==='salvage'?1.5:1));r.coins+=reward;r.hp=Math.min(r.maxHp,r.hp+r.maxHp*.18);this.showToast(`无尽首领击破 · 回复生命 +${reward} 金币`,3000);this.vibrate('heavy');}}return !!crit;
  },

  hurtPlayer(amount) { const r=this.run;if(r.invuln>0||this.phase!=='playing')return;if(r.shieldUp&&r.weapons.shield){const level=r.weapons.shield,w=WEAPONS.shield,s=this.stats(),evolved=r.evolved.includes('shield'),damage=w.damage*s.damage*(1+(level-1)*.24)*(evolved?1.55:1),radius=(140+level*8)*s.area*(evolved?1.3:1)*(1+(r.passives.thorn||0)*.08);r.shieldUp=false;r.invuln=.8;r.timers.shield=w.cooldown*s.cooldown*(1-(level-1)*.08)*(evolved?.82:1);r.enemies.forEach(e=>{const d=Math.max(1,distance(e,r));if(!e.dead&&d<radius+e.r){this.damageEnemy(e,damage,'shield');if(!e.dead){e.x=clamp(e.x+(e.x-r.x)/d*50,20,WORLD.width-20);e.y=clamp(e.y+(e.y-r.y)/d*50,20,WORLD.height-20);}}});if(evolved)r.hp=Math.min(r.maxHp,r.hp+r.maxHp*.05);r.particles.push({ring:true,skillEffect:'shield',effectSize:radius*2.15,x:r.x,y:r.y,radius,ttl:.5,maxTtl:.5,color:w.color});r.shake=Math.max(r.shake,5);this.vibrate('medium');return;}r.hp-=amount;r.invuln=.5;r.shake=7;this.playSound('hit');this.vibrate('light');const tl=r.passives.thorn||0;if(tl&&amount>0){const radius=110+10*tl,dmg=amount*(1+.5*tl);r.enemies.forEach(e=>{const d=Math.max(1,distance(e,r));if(!e.dead&&d<radius+e.r){this.damageEnemy(e,dmg,'thorn');if(!e.dead&&!e.bossId){e.x=clamp(e.x+(e.x-r.x)/d*30,20,WORLD.width-20);e.y=clamp(e.y+(e.y-r.y)/d*30,20,WORLD.height-20);}}});r.particles.push({ring:true,x:r.x,y:r.y,radius,ttl:.4,maxTtl:.4,color:'#c4544e'});}if(r.hp<=0){const pl=r.passives.phoenix||0;if(pl&&!r.phoenixUsed){r.phoenixUsed=true;r.hp=Math.round(r.maxHp*(.3+.1*pl));r.invuln=3;const wd=r.maxHp*.3;r.enemies.forEach(e=>{const d=Math.max(1,distance(e,r));if(!e.dead&&d<260+e.r){this.damageEnemy(e,wd,'phoenix');if(!e.dead&&!e.bossId){e.x=clamp(e.x+(e.x-r.x)/d*80,20,WORLD.width-20);e.y=clamp(e.y+(e.y-r.y)/d*80,20,WORLD.height-20);}}});for(let i=0;i<(this.meta.settings.lowQuality?6:14);i++)r.particles.push({ring:true,x:r.x,y:r.y,radius:40+i*22,ttl:.5+i*.05,maxTtl:.5+i*.05,color:i%2?'#ff9a55':'#ffd257'});r.shake=Math.max(r.shake,8);this.vibrate('heavy');this.showToast('不死鸟展翼 · 浴火重生',3000);return;}r.hp=0;this.finishRun('lose');} },

  updatePickups(dt,s) { const r=this.run;for(let i=r.pickups.length-1;i>=0;i--){const p=r.pickups[i],d=distance(p,r);if(d<s.pickup*2&&d>2){p.x+=(r.x-p.x)/d*150*dt;p.y+=(r.y-p.y)/d*150*dt;}if(d<s.pickup){r.pickups.splice(i,1);if(p.type==='xp')r.xp+=Math.round(p.value*(r.dailyRule==='abundance'?1.25:1));else if(p.type==='coin')r.coins+=p.value;else if(p.type==='potion'){const before=r.hp;r.hp=Math.min(r.maxHp,r.hp+r.maxHp*.25);if(r.hp>before)this.showToast(`生命恢复 +${Math.ceil(r.hp-before)}`,1200);}else if(p.type==='chest'){this.openChest();return;}}}if(r.xp>=r.xpNeed)this.levelUp(); },

  levelUp() { const r=this.run;if(this.phase!=='playing')return;r.xp-=r.xpNeed;r.level++;r.xpNeed=Math.round(15+10*Math.pow(r.level-1,1.3));this.phase='level';this.vibrate('medium');this.playSound('level_up');this.showChoices(); },
  buildChoices() { const r=this.run,pool=[];Object.keys(WEAPONS).forEach(id=>{if((r.weapons[id]||0)<5&&(r.weapons[id]||Object.keys(r.weapons).length<5))pool.push({kind:'weapon',id});});Object.keys(PASSIVES).forEach(id=>{if((r.passives[id]||0)<5&&(r.passives[id]||Object.keys(r.passives).length<5))pool.push({kind:'passive',id});});const out=[],lk=r.passives.luck||0,held=x=>x.kind==='weapon'?!!r.weapons[x.id]:x.kind==='passive'?!!r.passives[x.id]:false,take=list=>{if(!list.length)return null;const weights=list.map(x=>1+(held(x) ? .15*lk : 0)),total=weights.reduce((a,b)=>a+b,0);let roll=Math.random()*total,i=0;for(;i<weights.length-1&&roll>=weights[i];i++)roll-=weights[i];const x=list[i],pi=pool.indexOf(x);return pi>=0?pool.splice(pi,1)[0]:null;};if(r.lockedChoice){const i=pool.findIndex(x=>x.kind===r.lockedChoice.kind&&x.id===r.lockedChoice.id);i>=0?out.push(pool.splice(i,1)[0]):r.lockedChoice=null;}if(!out.some(held)){const weapons=pool.filter(x=>x.kind==='weapon'&&held(x)),current=weapons.length?weapons:pool.filter(held),x=take(current);if(x)out.push(x);}if(!out.some(x=>!held(x))){const x=take(pool.filter(x=>!held(x)));if(x)out.push(x);}while(out.length<3&&pool.length){const x=take(pool);if(x)out.push(x);}while(out.length<3)out.push(r.endless?{kind:'refine',id:'refine'}:{kind:'coin',id:'coin'});return out; },
  showChoices(reuse) { const r=this.run;if(!reuse)this.pendingChoices=this.buildChoices();const choices=this.pendingChoices.map(c=>{const locked=!!r.lockedChoice&&r.lockedChoice.kind===c.kind&&r.lockedChoice.id===c.id;if(c.kind==='weapon'){const d=WEAPONS[c.id],lv=r.weapons[c.id]||0;return{key:`w${c.id}`,icon:d.icon,name:d.name,levelText:lv?`Lv ${lv} → ${lv+1}`:'新武器',text:'提升伤害、范围或攻击频率',school:d.tag,tag:r.passives[d.passive]?'◆ 已满足进化配方':'武器能力',locked,lockable:true};}if(c.kind==='passive'){const d=PASSIVES[c.id],lv=r.passives[c.id]||0;return{key:`p${c.id}`,icon:d.icon,name:d.name,levelText:lv?`Lv ${lv} → ${lv+1}`:'新被动',text:d.text,school:d.tag,tag:'被动能力',locked,lockable:true};}if(c.kind==='refine')return{key:'refine',icon:'https://oss.zyg8.top/game/assets/passive-power.png',name:'无尽淬炼',levelText:`第 ${(r.refine||0)+1} 次淬炼`,text:'所有伤害 +6% · 最大生命 +4',school:'无尽成长',tag:'永久强化'};return{key:'coin',icon:'https://oss.zyg8.top/game/assets/pickup-coin.png',name:'金币补给',levelText:'补给',text:'获得 20 金币',school:'资源补给',tag:'资源'};});this.setData({rerolls:r.rerolls,modal:{type:'level',title:`等级提升 · Lv ${r.level}`,subtitle:'构筑强化 · 新能力 · 随机选择，可锁定一张',choices}}); },
  toggleChoiceLock(e) { const c=this.pendingChoices[Number(e.currentTarget.dataset.index)],r=this.run;if(!c||!['weapon','passive'].includes(c.kind))return;const same=r.lockedChoice&&r.lockedChoice.kind===c.kind&&r.lockedChoice.id===c.id;r.lockedChoice=same?null:{kind:c.kind,id:c.id};this.showChoices(true); },
  chooseUpgrade(e) { this.playSound('confirm');const c=this.pendingChoices[Number(e.currentTarget.dataset.index)],r=this.run;if(!c)return;if(r.lockedChoice&&r.lockedChoice.kind===c.kind&&r.lockedChoice.id===c.id)r.lockedChoice=null;if(c.kind==='weapon'){r.weapons[c.id]=(r.weapons[c.id]||0)+1;this.meta.discoveries.weapons[c.id]=true;this.saveMeta();}else if(c.kind==='passive')r.passives[c.id]=(r.passives[c.id]||0)+1;else if(c.kind==='refine'){r.refine=(r.refine||0)+1;r.maxHp+=4;r.hp=Math.min(r.maxHp,r.hp+4);}else r.coins+=20;this.phase='playing';this.setData({modal:emptyModal()});this.syncHud(true);if(r.xp>=r.xpNeed)this.levelUp();this.startCanvasLoop(); },
  reroll() { if(this.run.rerolls<=0)return;this.run.rerolls--;this.showChoices(); },

  openChest() { const r=this.run;this.phase='chest';this.playSound('chest');const eligible=Object.keys(r.weapons).filter(id=>r.weapons[id]>=5&&r.passives[WEAPONS[id].passive]&&!r.evolved.includes(id)),ready=Object.keys(r.weapons).filter(id=>r.weapons[id]>=4&&r.passives[WEAPONS[id].passive]&&!r.evolved.includes(id)).sort((a,b)=>r.weapons[b]-r.weapons[a]);let icon,name,text;if(eligible.length||ready.length){const id=eligible[0]||ready[0];r.weapons[id]=5;r.evolved.push(id);this.meta.discoveries.weapons[id]=true;this.meta.discoveries.evolved[id]=true;this.saveMeta();icon=WEAPONS[id].icon;name=`${WEAPONS[id].name} · 进化`;text=`${WEAPONS[id].tag}成型，联动效果全面强化`;}else{const ids=Object.keys(r.weapons).filter(id=>r.weapons[id]<5).sort((a,b)=>r.weapons[b]-r.weapons[a]);if(ids.length){const id=ids[0];r.weapons[id]++;this.meta.discoveries.weapons[id]=true;this.saveMeta();icon=WEAPONS[id].icon;name=`${WEAPONS[id].name} Lv${r.weapons[id]}`;text='最接近成型的武器获得升级';}else{r.coins+=20;icon='https://oss.zyg8.top/game/assets/pickup-coin.png';name='金币奖励';text='获得 20 金币';}}this.setData({modal:{type:'chest',title:'宝箱奖励',subtitle:'精英战利品',icon,rewardName:name,rewardText:text}}); },
  closeReward() { this.phase='playing';this.setData({modal:emptyModal()});this.syncHud(true);if(this.run.xp>=this.run.xpNeed)this.levelUp();this.startCanvasLoop(); },

  syncHud(force) { const r=this.run;if(!r)return;const phase=r.time<300?0:r.time<600?1:r.time<900?2:3,next=[300,600,900][phase];const boss=r.enemies.find(e=>e.special==='endlessboss')||r.enemies.find(e=>e.special==='finalboss')||r.enemies.find(e=>e.special==='midboss'),bossData=boss&&boss.bossId?BOSSES[boss.bossId]:null;let chapter=['第一幕 · 灰烬苏醒','第二幕 · 猎潮逼近','第三幕 · 长夜围城','终幕 · 灾厄降临'][phase],objective=r.horde?'击退怪物群潮':phase===3?'击败最终首领':`下一事件 ${timeText(next-r.time)}`;if(r.endless){chapter=`无尽轮回 · 第 ${r.endlessCycle} 层`;const ct=r.time-r.cycleStart,nextT=[60,110,150].find(t=>t>ct)||150;objective=boss?'击破无尽首领':r.horde?'击退怪物群潮':`下一事件 ${timeText(nextT-ct)}`;}const hazard=(r.hazards||[]).find(h=>r.time>=h.start&&r.time<h.end),hazardNames={fissure:'火焰裂缝',poison:'腐化毒雾',storm:'废墟风暴',dark:'深渊黑暗'};if(r.altar&&r.altar.active)objective=`净化祭坛 ${Math.floor(r.altar.progress/r.altar.need*100)}%`;else if(hazard)objective=`环境异变 · ${hazardNames[hazard.type]}`;const weaponList=Object.keys(r.weapons).map(id=>({id,name:WEAPONS[id].name,icon:WEAPONS[id].icon,level:r.weapons[id],evolved:r.evolved.includes(id)}));const passiveList=Object.keys(r.passives).map(id=>({id,name:PASSIVES[id].name,icon:PASSIVES[id].icon,level:r.passives[id]}));this.setData({hud:{hpPercent:clamp(r.hp/r.maxHp*100,0,100),xpPercent:clamp(r.xp/r.xpNeed*100,0,100),hpText:`${Math.ceil(r.hp)}/${Math.ceil(r.maxHp)}`,levelText:String(r.level).padStart(2,'0'),chapter,time:timeText(r.time),objective,coins:r.coins,kills:r.kills,weaponList,passiveList,bossVisible:!!boss,bossPercent:boss?clamp(boss.hp/boss.maxHp*100,0,100):100,bossName:bossData?`${bossData.name} · 阶段${boss.phase||1}`:boss&&boss.special==='finalboss'?'最终首领':'首领',hordeVisible:!!r.horde,hordeText:r.horde?(r.endless?`第 ${r.endlessCycle} 层群潮 · 待入场 ${r.horde.remaining}`:`第 ${r.horde.wave} 波 · 待入场 ${r.horde.remaining}`):''}}); },

  showToast(text, ms=2500) { clearTimeout(this.toastTimer);this.setData({toast:text});this.toastTimer=setTimeout(()=>this.setData({toast:''}),ms); },
  vibrate(level) { if(!this.data.settings.sound)return;try { if(level==='light')wx.vibrateShort({type:'light'});else wx.vibrateShort({type:level==='heavy'?'heavy':'medium'}); } catch (_) {} },

  drawSkillFrame(ctx,id,frame,x,y,width,height,rotation=0) {
    const w=WEAPONS[id],img=w&&w.effect&&this.loadCanvasImage(this.skillImages,id,w.effect);if(!img||!img.ready||!w||!w.effectFrames)return false;
    const cols=w.effectColumns||w.effectFrames,fw=img.width/cols,fh=img.height/Math.ceil(w.effectFrames/cols),index=frame%w.effectFrames;ctx.save();ctx.translate(x,y);ctx.rotate(rotation);ctx.drawImage(img,(index%cols)*fw,Math.floor(index/cols)*fh,fw,fh,-width/2,-height/2,width,height);ctx.restore();return true;
  },

  drawBossEffect(ctx,bossId,frame,x,y,size) {
    const d=BOSSES[bossId],img=d&&d.attackEffect&&this.loadCanvasImage(this.bossEffectImages,bossId,d.attackEffect);if(!img||!img.ready||!d||!d.effectFrames)return false;
    const fw=img.width/d.effectFrames,fh=img.height;ctx.drawImage(img,(frame%d.effectFrames)*fw,0,fw,fh,x-size/2,y-size/2,size,size);return true;
  },

  drawEnemy(ctx,e,r) {
    const monsterId=e.bossId||e.type,d=e.bossId?BOSSES[e.bossId]:ENEMIES[e.type],img=d&&this.loadCanvasImage(this.monsterImages,monsterId,d.sprite);ctx.save();ctx.translate(e.x,e.y);
    if(e.special){ctx.strokeStyle=e.special==='finalboss'?'#e85d68':'#f0bd69';ctx.lineWidth=3;ctx.globalAlpha=.8;ctx.beginPath();ctx.arc(0,0,e.r*1.3,0,Math.PI*2);ctx.stroke();ctx.globalAlpha=1;}
    if(e.warning>0&&!e.bossId){ctx.globalAlpha=clamp(e.warning/.42,0,1);ctx.strokeStyle=d.shot==='ember'?'#ff8556':'#b88aff';ctx.lineWidth=3;ctx.shadowColor=ctx.strokeStyle;ctx.shadowBlur=10;ctx.beginPath();ctx.arc(0,0,e.r*1.45,0,Math.PI*2);ctx.stroke();ctx.shadowBlur=0;ctx.globalAlpha=1;}
    [e.affix,e.affix2].filter(Boolean).forEach(id=>{const pulse=1+Math.sin(r.time*6+e.id)*.1;if(id==='swift'){const len=Math.max(1,distance(e,r)),tx=(e.x-r.x)/len,ty=(e.y-r.y)/len;ctx.fillStyle='rgba(105,105,255,.16)';for(let i=1;i<=2;i++){ctx.beginPath();ctx.ellipse(tx*e.r*i*.8,ty*e.r*i*.8,e.r*(1-i*.18),e.r*.65,0,0,Math.PI*2);ctx.fill();}}else if(id==='corpse'){ctx.strokeStyle='rgba(255,132,55,.75)';ctx.lineWidth=3;ctx.beginPath();ctx.arc(0,0,e.r*1.55*pulse,0,Math.PI*2);ctx.stroke();}else if(id==='healer'){ctx.strokeStyle='rgba(91,220,132,.48)';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,90,0,Math.PI*2);ctx.stroke();for(let i=0;i<8;i++){const a=i*Math.PI/4+r.time*.25;ctx.beginPath();ctx.moveTo(Math.cos(a)*82,Math.sin(a)*82);ctx.lineTo(Math.cos(a)*90,Math.sin(a)*90);ctx.stroke();}}else if(id==='shield'&&e.shield>0){ctx.strokeStyle='rgba(93,184,255,.82)';ctx.fillStyle='rgba(61,139,211,.1)';ctx.lineWidth=3;ctx.beginPath();for(let i=0;i<6;i++){const a=i*Math.PI/3-Math.PI/2,x=Math.cos(a)*e.r*1.75,y=Math.sin(a)*e.r*1.75;i?ctx.lineTo(x,y):ctx.moveTo(x,y);}ctx.closePath();ctx.fill();ctx.stroke();}else if(id==='split'){ctx.fillStyle='#83eb70';for(let i=0;i<4;i++){const a=i*Math.PI/2+r.time*.5;ctx.beginPath();ctx.arc(Math.cos(a)*e.r*1.45,Math.sin(a)*e.r*1.45,3,0,Math.PI*2);ctx.fill();}}else if(id==='teleport'){ctx.strokeStyle='#c17aff';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,-e.r*1.9);ctx.lineTo(e.r*.45,-e.r*1.45);ctx.lineTo(0,-e.r);ctx.lineTo(-e.r*.45,-e.r*1.45);ctx.closePath();ctx.stroke();}});
    if(img&&img.ready){const frames=d.frames||1,frame=Math.floor((r.time+e.id*.037)*(d.fps||6))%frames,fw=img.width/frames,fh=img.height,size=e.r*(e.bossId?5.2:e.special?5:4.2);ctx.save();ctx.scale(r.x<e.x?-1:1,1);ctx.drawImage(img,frame*fw,0,fw,fh,-size/2,-size*.54,size,size);ctx.restore();}else{ctx.save();ctx.rotate(Math.atan2(r.y-e.y,r.x-e.x)+Math.PI/2);ctx.fillStyle=ENEMIES[e.type].color;ctx.strokeStyle=e.special?'#f0bd69':'#11171c';ctx.lineWidth=e.special?4:2;ctx.beginPath();if(e.type==='runner'){ctx.moveTo(0,-e.r*1.3);ctx.lineTo(e.r*.8,e.r);ctx.lineTo(0,e.r*.55);ctx.lineTo(-e.r*.8,e.r);}else if(e.type==='thrower'){ctx.moveTo(0,-e.r*1.2);ctx.lineTo(e.r,0);ctx.lineTo(0,e.r*1.2);ctx.lineTo(-e.r,0);}else if(e.type==='guard'){ctx.moveTo(-e.r*.85,-e.r);ctx.lineTo(e.r*.85,-e.r);ctx.lineTo(e.r*.7,e.r*.7);ctx.lineTo(0,e.r*1.2);ctx.lineTo(-e.r*.7,e.r*.7);}else if(e.type==='summoner'){for(let i=0;i<8;i++){const a=i*Math.PI/4-Math.PI/2,rr=i%2?e.r*.55:e.r*1.2;ctx.lineTo(Math.cos(a)*rr,Math.sin(a)*rr);}}else{ctx.arc(0,0,e.r,0,Math.PI*2);}ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle=e.type==='bomber'?'#ff9d56':e.type==='summoner'?'#ba9ef5':'#dc6066';ctx.beginPath();ctx.arc(0,-e.r*.15,Math.max(2,e.r*.18),0,Math.PI*2);ctx.fill();ctx.restore();}if(e.poisonUntil>r.time){ctx.fillStyle='rgba(90,200,90,.25)';ctx.beginPath();ctx.ellipse(0,0,e.r*1.25,e.r*1.45,0,0,Math.PI*2);ctx.fill();const count=this.meta.settings.lowQuality?2:4;ctx.fillStyle='rgba(126,224,105,.55)';for(let i=0;i<count;i++){const a=r.time*(.7+i*.12)+i*1.7,rr=e.r*(.45+i*.2);ctx.beginPath();ctx.arc(Math.cos(a)*rr,Math.sin(a)*rr-e.r*.5,2+i%2,0,Math.PI*2);ctx.fill();}}if(r.time<(e.frozenUntil||0)){ctx.fillStyle='rgba(120,200,255,.4)';ctx.strokeStyle='#bceeff';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(0,0,e.r*1.28,e.r*1.48,0,0,Math.PI*2);ctx.fill();ctx.stroke();for(let i=0;i<5;i++){const a=i*Math.PI*.4;ctx.beginPath();ctx.moveTo(Math.cos(a)*e.r*.8,Math.sin(a)*e.r*.8);ctx.lineTo(Math.cos(a)*e.r*1.45,Math.sin(a)*e.r*1.45);ctx.stroke();}}ctx.restore();
  },

  draw() {
    const ctx=this.ctx,v=this.viewport;if(!ctx||!v)return;ctx.clearRect(0,0,v.width,v.height);ctx.fillStyle='#101820';ctx.fillRect(0,0,v.width,v.height);if(!this.run||this.data.screen!=='game')return;const r=this.run,cam={x:clamp(r.x-v.width/2,0,WORLD.width-v.width),y:clamp(r.y-v.height/2,0,WORLD.height-v.height)},sx=r.shake?rnd(-r.shake,r.shake):0,sy=r.shake?rnd(-r.shake,r.shake):0;ctx.save();ctx.translate(-cam.x+sx,-cam.y+sy);
    const g=ctx.createRadialGradient(WORLD.width/2,WORLD.height/2,80,WORLD.width/2,WORLD.height/2,1500);g.addColorStop(0,'#313b38');g.addColorStop(.42,'#222b2a');g.addColorStop(.78,'#171f20');g.addColorStop(1,'#0b1216');ctx.fillStyle=g;ctx.fillRect(0,0,WORLD.width,WORLD.height);

    ctx.save();ctx.lineCap='round';ctx.strokeStyle='#171d1d';ctx.lineWidth=176;ctx.beginPath();ctx.moveTo(-80,1180);ctx.bezierCurveTo(480,1010,690,640,1190,805);ctx.bezierCurveTo(1640,950,1940,610,2480,455);ctx.stroke();ctx.strokeStyle='#454742';ctx.lineWidth=142;ctx.globalAlpha=.28;ctx.stroke();ctx.strokeStyle='#77736a';ctx.lineWidth=2;ctx.globalAlpha=.2;ctx.stroke();ctx.restore();
    ctx.save();ctx.lineCap='round';ctx.strokeStyle='#151b1c';ctx.lineWidth=108;ctx.beginPath();ctx.moveTo(650,-60);ctx.bezierCurveTo(810,360,1090,510,1200,805);ctx.bezierCurveTo(1320,1120,1600,1320,1720,1680);ctx.stroke();ctx.strokeStyle='#66645d';ctx.lineWidth=1.5;ctx.globalAlpha=.2;ctx.stroke();ctx.restore();

    if(!this.meta.settings.lowQuality){ctx.strokeStyle='rgba(103,108,103,.15)';ctx.lineWidth=1;for(let x=70;x<WORLD.width;x+=190){for(let y=55;y<WORLD.height;y+=168){if(x<cam.x-100||x>cam.x+v.width+100||y<cam.y-100||y>cam.y+v.height+100)continue;const ox=((x+y)/7)%23;ctx.beginPath();ctx.moveTo(x-48+ox,y);ctx.lineTo(x+42+ox,y+((x/190)%2?7:-5));ctx.stroke();ctx.beginPath();ctx.moveTo(x,y-38);ctx.lineTo(x+5,y+34);ctx.stroke();}}for(let i=0;i<34;i++){const x=(i*431+157)%WORLD.width,y=(i*277+113)%WORLD.height;if(x<cam.x-100||x>cam.x+v.width+100||y<cam.y-100||y>cam.y+v.height+100)continue;const len=18+i%19;ctx.strokeStyle=i%5===0?'rgba(129,70,54,.25)':'rgba(8,13,15,.52)';ctx.lineWidth=i%5===0?2:1.5;ctx.beginPath();ctx.moveTo(x-len,y);ctx.lineTo(x-3,y+6+i%5);ctx.lineTo(x+9,y-5);ctx.lineTo(x+len,y+2);ctx.stroke();}}

    ctx.save();ctx.translate(WORLD.width/2,WORLD.height/2);ctx.fillStyle='rgba(8,15,17,.55)';ctx.beginPath();ctx.arc(0,0,126,0,Math.PI*2);ctx.fill();ctx.strokeStyle='rgba(91,151,154,.34)';ctx.lineWidth=4;ctx.beginPath();ctx.arc(0,0,108,.18,Math.PI*1.72);ctx.stroke();ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,76,Math.PI*.45,Math.PI*2.28);ctx.stroke();for(let i=0;i<12;i++){const a=i*Math.PI/6,rr=i%2?91:102;ctx.save();ctx.translate(Math.cos(a)*rr,Math.sin(a)*rr);ctx.rotate(a);ctx.strokeStyle='rgba(118,183,181,.34)';ctx.beginPath();ctx.moveTo(-5,-7);ctx.lineTo(0,7);ctx.lineTo(6,-5);ctx.stroke();ctx.restore();}ctx.restore();

    ctx.fillStyle='rgba(8,13,14,.58)';ctx.beginPath();ctx.ellipse(1930,1190,190,118,-.18,0,Math.PI*2);ctx.fill();ctx.strokeStyle='rgba(155,70,48,.3)';ctx.lineWidth=3;ctx.beginPath();ctx.ellipse(1930,1190,142,82,-.18,.35,Math.PI*1.7);ctx.stroke();for(let i=0;i<7;i++){const a=i*.86+.2,x=1930+Math.cos(a)*45,y=1190+Math.sin(a)*28;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+Math.cos(a)*(48+(i*17)%41),y+Math.sin(a)*(37+(i*13)%29));ctx.stroke();}

    for(let i=0;i<12;i++){const x=325+(i%4)*72+(i%2)*9,y=270+Math.floor(i/4)*88;ctx.fillStyle='rgba(7,11,13,.48)';ctx.beginPath();ctx.ellipse(x,y+16,20,7,0,0,Math.PI*2);ctx.fill();ctx.fillStyle=i%3===0?'#343b39':'#2b3232';ctx.strokeStyle='rgba(126,134,124,.28)';ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(x-11,y+12);ctx.lineTo(x-10,y-10);ctx.quadraticCurveTo(x,y-22,x+10,y-10);ctx.lineTo(x+11,y+12);ctx.closePath();ctx.fill();ctx.stroke();if(i%3===0){ctx.beginPath();ctx.moveTo(x,y-14);ctx.lineTo(x,y+5);ctx.moveTo(x-6,y-6);ctx.lineTo(x+6,y-6);ctx.stroke();}}

    for(let i=0;i<7;i++){const x=255+(i*137)%620,y=1110+(i*83)%330,h=42+i%3*16;ctx.strokeStyle='#171c1c';ctx.lineWidth=7;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(x,y+20);ctx.lineTo(x,y-h);ctx.lineTo(x-18-i%2*8,y-h-19);ctx.moveTo(x,y-h+12);ctx.lineTo(x+25,y-h-10);ctx.moveTo(x-2,y-h+27);ctx.lineTo(x-25,y-h+10);ctx.stroke();ctx.strokeStyle='rgba(82,91,84,.23)';ctx.lineWidth=2;ctx.stroke();}

    ctx.fillStyle='rgba(18,24,23,.72)';ctx.strokeStyle='rgba(105,109,99,.25)';ctx.lineWidth=3;ctx.fillRect(1770,260,360,38);ctx.strokeRect(1770,260,360,38);ctx.fillRect(2088,260,42,280);ctx.strokeRect(2088,260,42,280);ctx.fillRect(1770,500,210,40);ctx.strokeRect(1770,500,210,40);for(let i=0;i<14;i++){const x=1745+(i*71)%420,y=240+(i*47)%340;ctx.fillStyle='#242a28';ctx.beginPath();ctx.ellipse(x,y,14+i%12,7+i%5,i*.4,0,Math.PI*2);ctx.fill();}

    if(!this.meta.settings.lowQuality){for(let i=0;i<22;i++){const x=(i*347+123)%WORLD.width,y=(i*619+91)%WORLD.height;if(x<cam.x-160||x>cam.x+v.width+160||y<cam.y-100||y>cam.y+v.height+100)continue;ctx.fillStyle='rgba(170,183,170,.025)';ctx.beginPath();ctx.ellipse(x,y,85+i%45,24+i%18,i*.31,0,Math.PI*2);ctx.fill();}}
    ctx.strokeStyle='#70787555';ctx.lineWidth=6;ctx.strokeRect(4,4,WORLD.width-8,WORLD.height-8);
    if(r.altar&&r.altar.active){const a=r.altar,p=a.progress/a.need;ctx.fillStyle='rgba(67,147,157,.11)';ctx.strokeStyle='rgba(111,220,224,.7)';ctx.lineWidth=3;ctx.beginPath();ctx.arc(a.x,a.y,a.radius,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.strokeStyle='#f2c86f';ctx.lineWidth=7;ctx.beginPath();ctx.arc(a.x,a.y,a.radius+9,-Math.PI/2,-Math.PI/2+Math.PI*2*p);ctx.stroke();ctx.fillStyle='#28383b';ctx.strokeStyle='#8bd7d7';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(a.x,a.y-34);ctx.lineTo(a.x+25,a.y+24);ctx.lineTo(a.x-25,a.y+24);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle='#d7f8ed';ctx.beginPath();ctx.arc(a.x,a.y-5,6,0,Math.PI*2);ctx.fill();}
    (r.supplies||[]).forEach(s=>{ctx.fillStyle='#3b3327';ctx.strokeStyle='#d7ad62';ctx.lineWidth=2;ctx.fillRect(s.x-18,s.y-13,36,26);ctx.strokeRect(s.x-18,s.y-13,36,26);ctx.fillStyle='#74c6d9';ctx.fillRect(s.x-3,s.y-13,6,26);ctx.fillRect(s.x-18,s.y-3,36,6);});
    (r.hazards||[]).forEach(h=>{if(r.time<h.start||r.time>=h.end)return;if(h.type==='poison'){ctx.fillStyle='rgba(74,112,54,.2)';ctx.strokeStyle='rgba(131,188,83,.55)';ctx.lineWidth=3;ctx.beginPath();ctx.arc(h.x,h.y,h.radius,0,Math.PI*2);ctx.fill();ctx.stroke();for(let i=0;i<(this.meta.settings.lowQuality?4:9);i++){const a=i*2.37+r.time*.12,rr=h.radius*(.18+(i%4)*.2);ctx.fillStyle='rgba(151,194,92,.16)';ctx.beginPath();ctx.arc(h.x+Math.cos(a)*rr,h.y+Math.sin(a)*rr,22+i%3*8,0,Math.PI*2);ctx.fill();}}else if(h.type==='storm'){const angle=h.angle||0,dx=Math.cos(angle),dy=Math.sin(angle);ctx.strokeStyle='rgba(161,215,230,.2)';ctx.lineWidth=2;for(let i=0;i<(this.meta.settings.lowQuality?7:15);i++){const x=cam.x+(i*173+r.time*90)%v.width,y=cam.y+(i*97)%v.height;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+dx*75,y+dy*75);ctx.stroke();}}});
    r.zones.forEach(z=>{if(z.type==='fire'){const frame=z.age<.72?Math.min(11,Math.floor(z.age/.72*12)):12+Math.floor((z.age-.72)*12)%6;this.drawSkillFrame(ctx,'flask',frame,z.x,z.y,z.radius*2.1,z.radius*2.1);return;}if(z.type==='poison'){const frame=Math.floor(z.age*12)%6;if(this.drawSkillFrame(ctx,'plague',frame,z.x,z.y,z.radius*2.2,z.radius*2.2))return;const pulse=.18+.06*Math.sin(z.age*7);ctx.fillStyle=`rgba(70,145,55,${pulse})`;ctx.strokeStyle='rgba(126,217,87,.72)';ctx.lineWidth=3;ctx.beginPath();ctx.arc(z.x,z.y,z.radius*(.96+.025*Math.sin(z.age*5)),0,Math.PI*2);ctx.fill();ctx.stroke();for(let i=0;i<(this.meta.settings.lowQuality?3:6);i++){const a=i*Math.PI/3+z.age*.35,rr=z.radius*(.25+(i%3)*.22);ctx.fillStyle='rgba(157,232,102,.42)';ctx.beginPath();ctx.arc(z.x+Math.cos(a)*rr,z.y+Math.sin(a)*rr,3+i%2,0,Math.PI*2);ctx.fill();}return;}if(z.type==='totem'){ctx.strokeStyle='rgba(143,201,168,.2)';ctx.lineWidth=2;ctx.beginPath();ctx.arc(z.x,z.y,z.range,0,Math.PI*2);ctx.stroke();const frame=Math.floor(z.age*8)%6;if(this.drawSkillFrame(ctx,'totem',frame,z.x,z.y,58,58))return;ctx.fillStyle='#283632';ctx.strokeStyle='#8fc9a8';ctx.lineWidth=2;ctx.fillRect(z.x-9,z.y-17,18,34);ctx.strokeRect(z.x-9,z.y-17,18,34);ctx.beginPath();ctx.moveTo(z.x-11,z.y-17);ctx.lineTo(z.x,z.y-34);ctx.lineTo(z.x+11,z.y-17);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle=`rgba(157,244,201,${.45+.35*Math.sin(z.age*8)})`;ctx.shadowColor='#8fc9a8';ctx.shadowBlur=10;ctx.beginPath();ctx.arc(z.x,z.y-23,4,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;return;}if(z.type==='gravity'){const frame=Math.floor(z.age*12)%6;if(this.drawSkillFrame(ctx,'gravity',frame,z.x,z.y,z.radius*1.7,z.radius*1.7))return;ctx.fillStyle=z.hit?'rgba(118,82,184,.08)':'rgba(50,32,83,.22)';ctx.beginPath();ctx.arc(z.x,z.y,z.radius,0,Math.PI*2);ctx.fill();ctx.strokeStyle='rgba(167,139,250,.58)';ctx.lineWidth=2;for(let i=0;i<3;i++){const rr=z.hit?z.radius:Math.max(8,z.radius*(1-((z.age*.8+i/3)%1)));ctx.beginPath();ctx.arc(z.x,z.y,rr,0,Math.PI*2);ctx.stroke();}return;}if(z.hit&&z.effect){const frame=Math.min(5,Math.floor((z.age-(z.hitAt||z.age))*12));if(this.drawBossEffect(ctx,z.effect,frame,z.x,z.y,z.radius*2.3))return;}const pulse=!z.hit ? .28+.16*Math.sin(z.age*18) : .12;ctx.fillStyle=`rgba(175,32,50,${pulse})`;ctx.strokeStyle=z.hit?'#ff9b72':'#ed5a64';ctx.lineWidth=3;ctx.beginPath();ctx.arc(z.x,z.y,z.radius,0,Math.PI*2);ctx.fill();ctx.stroke();});
    r.bullets.forEach(b=>{ctx.save();ctx.translate(b.x,b.y);ctx.rotate(Math.atan2(b.vy,b.vx));const ember=b.kind==='ember';ctx.fillStyle=ember?'#ff7045':'#b57cff';ctx.shadowColor=ember?'#ff4b2f':'#875cff';ctx.shadowBlur=12;ctx.beginPath();if(ember){ctx.moveTo(b.r+3,0);ctx.lineTo(-b.r,b.r*.72);ctx.lineTo(-b.r-4,0);ctx.lineTo(-b.r,-b.r*.72);ctx.closePath();}else ctx.arc(0,0,b.r,0,Math.PI*2);ctx.fill();ctx.strokeStyle=ember?'#ffd08a':'#d9c5ff';ctx.lineWidth=1.5;ctx.stroke();ctx.restore();});
    r.pickups.forEach(p=>{ctx.save();ctx.translate(p.x,p.y);if(p.type==='xp'){ctx.fillStyle='#50d8ff';ctx.shadowColor='#50d8ff';ctx.shadowBlur=10;ctx.beginPath();ctx.moveTo(0,-9);ctx.lineTo(7,0);ctx.lineTo(0,9);ctx.lineTo(-7,0);ctx.closePath();ctx.fill();}else if(p.type==='coin'){ctx.fillStyle='#e3ae47';ctx.beginPath();ctx.arc(0,0,7,0,Math.PI*2);ctx.fill();}else if(p.type==='potion'){ctx.shadowColor='#ff4e58';ctx.shadowBlur=12;ctx.fillStyle='#d9c7a0';ctx.fillRect(-4,-10,8,4);ctx.fillStyle='#5b171d';ctx.strokeStyle='#ff9a86';ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(-5,-6);ctx.lineTo(-8,-1);ctx.lineTo(-7,8);ctx.quadraticCurveTo(0,12,7,8);ctx.lineTo(8,-1);ctx.lineTo(5,-6);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle='#ed4e55';ctx.fillRect(-6,2,12,6);ctx.shadowBlur=0;}else{ctx.fillStyle='#d3a653';ctx.fillRect(-11,-8,22,16);ctx.strokeStyle='#f2cf82';ctx.strokeRect(-11,-8,22,16);}ctx.restore();});
    r.enemies.forEach(e=>{const pad=Math.max(100,e.r*(e.bossId?3:e.special?2.7:2.2));if(e.x<cam.x-pad||e.x>cam.x+v.width+pad||e.y<cam.y-pad||e.y>cam.y+v.height+pad)return;ctx.fillStyle='#0008';ctx.beginPath();ctx.ellipse(e.x,e.y+e.r*.7,e.r*1.2,e.r*.45,0,0,Math.PI*2);ctx.fill();this.drawEnemy(ctx,e,r);if(e.special||e.affix){const bw=Math.max(28,e.r*2),bx=e.x-bw/2,by=e.y-e.r-13;ctx.fillStyle='#341014';ctx.fillRect(bx,by,bw,4);ctx.fillStyle='#dc535c';ctx.fillRect(bx,by,bw*Math.max(0,e.hp/e.maxHp),4);if(e.maxShield){ctx.fillStyle='rgba(16,40,62,.9)';ctx.fillRect(bx,by-5,bw,3);ctx.fillStyle='#66b9ff';ctx.fillRect(bx,by-5,bw*clamp((e.shield||0)/e.maxShield,0,1),3);}}});
    r.projectiles.forEach(p=>{const w=WEAPONS[p.id],frame=w.effectFrames?Math.floor((p.age||0)*(w.effectFps||12))%w.effectFrames:0,angle=Math.atan2(p.vy,p.vx),size=p.id==='blade'?42:p.id==='arrow'?46:p.id==='raven'?48:p.id==='spike'?48:p.r*2.4,height=p.id==='spike'?24:size;if(this.drawSkillFrame(ctx,p.id,frame,p.x,p.y,size,height,angle))return;if(p.id==='spike'){ctx.save();ctx.translate(p.x,p.y);ctx.rotate(angle);ctx.fillStyle='#8ad8ff';ctx.strokeStyle='#d9f7ff';ctx.lineWidth=1.5;ctx.shadowColor='#7bd8ff';ctx.shadowBlur=9;ctx.beginPath();ctx.moveTo(14,0);ctx.lineTo(-2,7);ctx.lineTo(-11,0);ctx.lineTo(-2,-7);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore();return;}ctx.fillStyle=w.color;ctx.shadowColor=w.color;ctx.shadowBlur=8;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;});
    if(r.weapons.ring){const radius=(72+r.weapons.ring*6)*this.stats().area,frame=Math.floor(r.time*12)%6;ctx.strokeStyle='rgba(107,189,231,.3)';ctx.lineWidth=3;ctx.beginPath();ctx.arc(r.x,r.y,radius,0,Math.PI*2);ctx.stroke();for(let i=0;i<4;i++){const a=r.time*1.25+i*Math.PI/2;this.drawSkillFrame(ctx,'ring',frame,r.x+Math.cos(a)*radius,r.y+Math.sin(a)*radius,44,44,a+Math.PI/2);}}
    const character=CHARACTERS.find(c=>c.id===r.character)||CHARACTERS[0],hero=this.loadCanvasImage(this.heroImages,character.id,character.sprite);ctx.save();ctx.translate(r.x,r.y);if(r.invuln>0&&Math.floor(r.invuln*14)%2===0)ctx.globalAlpha=.45;if(hero&&hero.ready){const moving=Math.hypot((this.input&&this.input.x)||0,(this.input&&this.input.y)||0)>.08,frame=moving?Math.floor(r.time*character.fps)%character.frames:0,fw=hero.width/character.frames,fh=hero.height,size=64;ctx.scale(r.lastX<0?-1:1,1);ctx.drawImage(hero,frame*fw,0,fw,fh,-size/2,-size*.6,size,size);}else{const face=Math.atan2(r.lastY,r.lastX);ctx.rotate(face+Math.PI/2);ctx.fillStyle='#263e50';ctx.strokeStyle='#c0e0ef';ctx.lineWidth=2.5;ctx.beginPath();ctx.moveTo(0,-20);ctx.lineTo(12,-3);ctx.lineTo(15,17);ctx.lineTo(0,10);ctx.lineTo(-15,17);ctx.lineTo(-12,-3);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillStyle='#d5c2a5';ctx.beginPath();ctx.arc(0,-13,5,0,Math.PI*2);ctx.fill();}ctx.restore();
    if(r.tome&&r.tome.on&&r.weapons.tome){const level=r.weapons.tome,evolved=r.evolved.includes('tome'),count=2+Math.floor(level/2)+(evolved?2:0),radius=95*this.stats().area;for(let i=0;i<count;i++){const a=(r.tomeAngle||0)+i*Math.PI*2/count,x=r.x+Math.cos(a)*radius,y=r.y+Math.sin(a)*radius;if(this.drawSkillFrame(ctx,'tome',Math.floor(r.time*10)%6,x,y,42,42,a+Math.PI/2))continue;ctx.save();ctx.translate(x,y);ctx.rotate(a+Math.PI/2);ctx.fillStyle='#534923';ctx.strokeStyle='#f0d47b';ctx.lineWidth=1.5;ctx.shadowColor='#c9b46a';ctx.shadowBlur=8;ctx.fillRect(-13,-8,12,16);ctx.fillRect(1,-8,12,16);ctx.strokeRect(-13,-8,12,16);ctx.strokeRect(1,-8,12,16);ctx.beginPath();ctx.moveTo(0,-9);ctx.lineTo(0,9);ctx.stroke();ctx.restore();}}
    if(r.shieldUp){const radius=46+Math.sin(r.time*5)*2;ctx.save();ctx.translate(r.x,r.y);ctx.fillStyle='rgba(72,151,173,.13)';ctx.strokeStyle='rgba(255,214,107,.82)';ctx.lineWidth=3;ctx.shadowColor='#68d8e8';ctx.shadowBlur=12;ctx.beginPath();for(let i=0;i<6;i++){const a=i*Math.PI/3-Math.PI/2,x=Math.cos(a)*radius,y=Math.sin(a)*radius;i?ctx.lineTo(x,y):ctx.moveTo(x,y);}ctx.closePath();ctx.fill();ctx.stroke();ctx.restore();}
    r.particles.forEach(p=>{ctx.globalAlpha=p.thorns?clamp(p.ttl/.14,0,1):clamp(p.ttl/(p.maxTtl||.5),0,1);if(p.skillEffect){const iw=p.effectSize||p.radius*2||72,frame=Math.min(5,Math.floor((1-p.ttl/Math.max(.01,p.maxTtl||.4))*6));if(this.drawSkillFrame(ctx,p.skillEffect,frame,p.x,p.y,iw,p.effectHeight||(p.skillEffect==='beam'?Math.max(46,iw*.42):iw),p.angle||0))return;}if(p.lightning){const pts=p.points;if(!pts||pts.length<2)return;ctx.save();ctx.lineJoin='round';ctx.lineCap='round';ctx.shadowColor='#62caff';ctx.shadowBlur=16;ctx.strokeStyle='rgba(73,174,255,.7)';ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(pts[0].x,pts[0].y);for(let i=1;i<pts.length;i++)ctx.lineTo(pts[i].x,pts[i].y);ctx.stroke();ctx.shadowBlur=7;ctx.strokeStyle='#effcff';ctx.lineWidth=2;ctx.stroke();ctx.restore();}else if(p.ring){ctx.strokeStyle=p.color;ctx.lineWidth=5;ctx.beginPath();ctx.arc(p.x,p.y,p.radius,0,Math.PI*2);ctx.stroke();}else if(p.thorns){const frame=Math.min(5,Math.floor((1-p.ttl/(p.maxTtl||.55))*6));if(this.drawSkillFrame(ctx,'beam',frame,p.x,p.y,p.length,145,p.angle))return;ctx.save();ctx.translate(p.x,p.y);ctx.rotate(p.angle);const life=1-clamp(p.ttl/(p.maxTtl||.55),0,1),count=12;for(let i=0;i<count;i++){const grow=clamp((life-i/count*.72)*5,0,1);if(!grow)continue;const x=30+i*(p.length-55)/(count-1),side=i%2?1:-1,height=(20+i%3*7)*grow;ctx.fillStyle='rgba(38,16,18,.72)';ctx.beginPath();ctx.ellipse(x,0,17,7,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#281517';ctx.strokeStyle=p.color;ctx.lineWidth=2;ctx.shadowColor='#b93425';ctx.shadowBlur=7;ctx.beginPath();ctx.moveTo(x-10,side*4);ctx.lineTo(x+2,side*-height);ctx.lineTo(x+10,side*3);ctx.closePath();ctx.fill();ctx.stroke();ctx.shadowBlur=0;ctx.strokeStyle='#ff9a55';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(x+1,side*-height*.72);ctx.lineTo(x+3,side*-height*.22);ctx.stroke();}ctx.restore();}else if(p.book){ctx.fillStyle=p.color;ctx.fillRect(p.x-p.radius,p.y-p.radius*.65,p.radius*2,p.radius*1.3);}else{if(p.flash){ctx.shadowColor=p.color;ctx.shadowBlur=18;}ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.radius,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;}});ctx.globalAlpha=1;r.damageText.forEach(t=>{ctx.globalAlpha=clamp(t.ttl/.5,0,1);ctx.fillStyle=t.color;ctx.font='bold 14px serif';ctx.textAlign='center';ctx.fillText(String(t.text),t.x,t.y);});ctx.globalAlpha=1;const dark=(r.hazards||[]).find(h=>h.type==='dark'&&r.time>=h.start&&r.time<h.end);if(dark){const fog=ctx.createRadialGradient(r.x,r.y,125,r.x,r.y,310);fog.addColorStop(0,'rgba(0,0,0,0)');fog.addColorStop(.55,'rgba(0,0,0,.28)');fog.addColorStop(1,'rgba(0,0,0,.88)');ctx.fillStyle=fog;ctx.fillRect(cam.x,cam.y,v.width,v.height);}ctx.restore();
  },
});
